In [5]:
import csv
import os
import random
import pickle
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import sklearn
import warnings
import skbold
from skbold.preproc import ConfoundRegressor
from scipy.stats import pearsonr
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [15]:
# Define ConfoundRegressor: skbold
def confound_regressor_skbold(features_train, features_test, confounds_train, confounds_test):
    # Scale features (train and test sets)
    scaler_features = StandardScaler()
    features_train_scaled = scaler_features.fit_transform(features_train)
    features_test_scaled = scaler_features.transform(features_test)
    
    # Scale confounds (train and test sets)
    scaler_confounds = StandardScaler()
    confounds_train_scaled = scaler_confounds.fit_transform(confounds_train)
    confounds_test_scaled = scaler_confounds.transform(confounds_test)

    # Convert full sets into np.array
    features_full_scaled_np = np.array(pd.concat([pd.DataFrame(features_train_scaled, columns = features_train.columns), pd.DataFrame(features_test_scaled, columns = features_test.columns)], axis=0))
    confounds_full_scaled_np = np.array(pd.concat([pd.DataFrame(confounds_train_scaled, columns = confounds_train.columns), pd.DataFrame(confounds_test_scaled, columns = confounds_test.columns)], axis=0))
    
    # Define ConfoundRegressor on a FULL set (train and test)
    cfr = ConfoundRegressor(confound=confounds_full_scaled_np, X=features_full_scaled_np)
    features_train_corrected = cfr.fit_transform(features_train_scaled)
    features_test_corrected = cfr.transform(features_test_scaled)


    return features_train_corrected, features_test_corrected, features_train_scaled, features_test_scaled, scaler_features

In [7]:
amplitudes_21 = pd.read_csv("/media/hcs-sci-psy-narun/IBu/UK_BB/ukbbdata/Resting_State/rsfMRI_matrices/amplitudes_tables/21/amplitudes_21_fin_CLEAN.csv")
amplitudes_55 = pd.read_csv("/media/hcs-sci-psy-narun/IBu/UK_BB/ukbbdata/Resting_State/rsfMRI_matrices/amplitudes_tables/55/amplitudes_55_fin_CLEAN.csv")
full_correlation_21 = pd.read_csv('/media/hcs-sci-psy-narun/IBu/UK_BB/ukbbdata/Resting_State/rsfMRI_matrices/full_corr_tables/21/fcorr_21_instance_2_FINAL.csv')
full_correlation_55 = pd.read_csv('/media/hcs-sci-psy-narun/IBu/UK_BB/ukbbdata/Resting_State/rsfMRI_matrices/full_corr_tables/55/fcorr_55_instance_2_FINAL.csv')
partial_correlation_21 = pd.read_csv("/media/hcs-sci-psy-narun/IBu/UK_BB/ukbbdata/Resting_State/rsfMRI_matrices/partial_corr_tables/21/pcorr_21_instance_2_FINAL.csv")
partial_correlation_55 = pd.read_csv("/media/hcs-sci-psy-narun/IBu/UK_BB/ukbbdata/Resting_State/rsfMRI_matrices/partial_corr_tables/55/pcorr_55_instance_2_FINAL.csv")

Remember that renamed files are here: '/media/hcs-sci-psy-narun/IBu/UK_BB/ukbbdata/Resting_State/rsfMRI_matrices/amplitudes_tables/21/{df}_fin_renamed'

In [8]:
# Define modalities
modalities = [
'amplitudes_21',
'amplitudes_55',
'full_correlation_21',
'full_correlation_55',
'partial_correlation_21',
'partial_correlation_55']

In [18]:

confounds = pd.read_csv('/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/resting_files/rs_confounds.csv')

# these are the same confounds as at '/media/hcs-sci-psy-narun/IBu/UK_BB/ML_DATASETS/Brain/rsMRI/rs_confounds_fin_full.csv' saved at ICA_Confounds step

warnings.simplefilter(action='ignore', category=FutureWarning)

############## 1
seed = 42

for modality in modalities:

    print(f'Started {modality}', flush=True)

    file = pd.read_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/resting_files/{modality}.csv').rename(columns={'ID': 'eid'})

    folds = ["0", "1", "2", "3", "4"]
    pls_result = {}
    
    # Match confounds to MRI
    print(f'Matching brain data to confounds in {modality}', flush=True)

    conf_to_brain_match = pd.merge(confounds, file['eid'], on='eid')
    brain_to_conf_match = pd.merge(conf_to_brain_match['eid'], file, on='eid')

    for fold in folds:

        train_id = pd.read_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/g_factor_5_folds_python/fold_{fold}/train_id_fold_{fold}.csv')
        test_id = pd.read_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/g_factor_5_folds_python/fold_{fold}/test_id_fold_{fold}.csv')
        
        # Upload g-factor with ID
        g_train_full = pd.read_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/g_factor/g_train_with_id_fold_{fold}.csv')
        g_test_full = pd.read_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/g_factor/g_test_with_id_fold_{fold}.csv')

    
        # Match brain data to cognitive data
        print(f'Matching brain data to confounds in {modality}', flush=True)
        brain_train, brain_test, brain_train_id, brain_test_id = pd.merge(brain_to_conf_match, train_id, on='eid').drop(columns=['eid']), pd.merge(brain_to_conf_match, test_id, on='eid').drop(columns=['eid']), pd.merge(brain_to_conf_match, train_id, on='eid')['eid'], pd.merge(brain_to_conf_match, test_id, on='eid')['eid']

        brain_train.to_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/suppl/{modality}_train_fold_{fold}.csv', index=False)
        brain_test.to_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/suppl/{modality}_test_fold_{fold}.csv', index=False)
        brain_train_id.to_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/suppl/{modality}_train_id_fold_{fold}.csv', index=False)
        brain_test_id.to_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/suppl/{modality}_test_id_fold_{fold}.csv', index=False)
        
        ############## 2
        print(f'Matching confounds to {modality} fold {fold}', flush=True)
        
        # Match confounds to MRI
        brain_conf_train, brain_conf_test = pd.merge(conf_to_brain_match, brain_train_id, on='eid').drop(columns=['eid']), pd.merge(conf_to_brain_match, brain_test_id, on='eid').drop(columns=['eid'])
        brain_conf_train.to_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/suppl/{modality}_conf_train_fold_{fold}.csv', index=False)
        brain_conf_test.to_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/suppl/{modality}_conf_test_fold_{fold}.csv', index=False)
        
        ############## 3
        print(f'Matching g-factor to {modality} fold {fold}', flush=True)
        
        # Match g-factor back to MRI
        g_train, g_test, g_train_id, g_test_id = pd.merge(g_train_full, brain_train_id, on='eid').drop(columns=['eid']), pd.merge(g_test_full, brain_test_id, on='eid').drop(columns=['eid']), pd.merge(g_train_full, brain_train_id, on='eid')['eid'], pd.merge(g_test_full, brain_test_id, on='eid')['eid']
        g_train.to_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/suppl/g_train_{modality}_matched_fold_{fold}.csv', index=False)
        g_test.to_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/suppl/g_test_{modality}_matched_fold_{fold}.csv', index=False)
        
        ############## 4
        print(f'Applying ConfoundRegressor to {modality} fold {fold}', flush=True)
        
        # Apply ConfoundRegressor
        features_train_corr, features_test_corr, features_train_scaled, features_test_scaled, scaler_features = confound_regressor_skbold(brain_train, brain_test, brain_conf_train, brain_conf_test)
        pd.DataFrame(features_train_corr, columns = brain_train.columns).to_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/scaling/{modality}_train_corr_{fold}.csv', index=False)
        pd.DataFrame(features_test_corr, columns = brain_test.columns).to_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/scaling/{modality}_test_corr_{fold}.csv', index=False)
        
        pd.DataFrame(features_train_scaled, columns = brain_train.columns).to_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/scaling/{modality}_train_scaled_{fold}.csv', index=False)
        pd.DataFrame(features_test_scaled, columns = brain_test.columns).to_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/scaling/{modality}_test_scaled_{fold}.csv', index=False)
        
        with open(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/scaling/scaler_features_{modality}_fold_{fold}.pkl', "wb") as f:
            pickle.dump(scaler_features, f)

        # Initiate and run PLS
        parameters = {'n_components': range(1, 36, 1)}
        pls = PLSRegression()
        model = GridSearchCV(pls, parameters, scoring = 'neg_mean_absolute_error', cv=KFold(10, shuffle = True, random_state=seed), verbose=4, n_jobs = 15)
        
        
        print(f'Fitting PLS to {modality} fold {fold}', flush=True)
        model.fit(features_train_corr, np.array(g_train))
        
        print(f'Model parameters for fold {fold}:', model.cv_results_['params'])
        print(f'Mean test score for fold {fold}:', model.cv_results_['mean_test_score'])
        print(f'Rank test score for fold {fold}:', model.cv_results_['rank_test_score'])
        print(model)
        
        print(f'Saving PLS model for {modality} fold {fold}')
        with open(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/models/pkl/{modality}_model_fold_{fold}.pkl', "wb") as f:
            pickle.dump(model, f)
            
        print(f'Best params in fold {fold} = ', model.best_params_)
        print(f'Best score (neg_mean_absolute_error) in fold {fold} = ', model.best_score_)
            
        # Predict the values
        print(f'Predicting & saving g_test for {modality} fold {fold}', flush=True)
        g_pred_test = model.predict(np.array(features_test_corr))
        pd.DataFrame(g_pred_test, columns=['g predicted test']).to_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/g_pred/{modality}_test_fold_{fold}.csv')

        g_pred_test_with_id = pd.concat([g_test_id.astype(int), pd.DataFrame(g_pred_test, columns=['g predicted test'])], axis=1).to_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/g_pred/{modality}_g_pred_test_id_fold_{fold}.csv')

        
        print(f'Predicting & saving g_train for {modality} fold {fold}', flush=True)
        g_pred_train = model.predict(np.array(features_train_corr))
        pd.DataFrame(g_pred_train, columns=['g predicted train']).to_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/g_pred/{modality}_g_pred_train_fold_{fold}.csv')
        

        g_pred_train_with_id = pd.concat([g_train_id.astype(int), pd.DataFrame(g_pred_train, columns=['g predicted train'])], axis=1).to_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/g_pred/{modality}_g_pred_train_id_fold_{fold}.csv')
        
            
        print(f"Fold = {fold}")
        print("----------")
        print("MSE = ", mean_squared_error(np.array(g_test)[:,0], g_pred_test[:,0]))
        print("MAE = ", mean_absolute_error(np.array(g_test)[:,0], g_pred_test[:,0]))
        print("R2 = ", r2_score(np.array(g_test)[:,0], g_pred_test[:,0]))
        print("Pearson's r = ", pearsonr(np.array(g_test)[:,0], g_pred_test[:,0]))
        print("----------")
            
        pls_result['fold'] = fold
        pls_result['modality'] = modality
        pls_result['n_components'] = model.best_params_
        pls_result['MSE'] = mean_squared_error(np.array(g_test)[:,0], g_pred_test[:,0])
        pls_result['MAE'] = mean_absolute_error(np.array(g_test)[:,0], g_pred_test[:,0])
        pls_result['R2'] = r2_score(np.array(g_test)[:,0], g_pred_test[:,0])
        pls_result['Pearson r'] = pearsonr(np.array(g_test)[:,0], g_pred_test[:,0])
            
        with open(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/models/csv/{modality}_fold_{fold}_PLS_result.csv', 'a', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=pls_result.keys())
            writer.writerow(pls_result)
            
        pls_result.clear()
        
        corr, pval = stats.pearsonr(np.squeeze(np.array(g_test)), np.squeeze(g_pred_test))
        r2 = r2_score(np.squeeze(np.array(g_test)), np.squeeze(g_pred_test))
        mse = mean_squared_error(np.squeeze(np.array(g_test)), np.squeeze(g_pred_test))
        result = pd.DataFrame([modality, fold, corr, pval, r2, mse, model.best_params_], index=['Modality', 'Fold', 'Correlation', 'P-value', 'R2', 'MSE', 'n components'], columns=['Values']).to_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/models/csv/{modality}_fold_{fold}_full_result.csv')

Started amplitudes_21
Matching brain data to confounds in amplitudes_21
Matching brain data to confounds in amplitudes_21
Matching confounds to amplitudes_21 fold 0
Matching g-factor to amplitudes_21 fold 0
Applying ConfoundRegressor to amplitudes_21 fold 0
Fitting PLS to amplitudes_21 fold 0
Fitting 10 folds for each of 35 candidates, totalling 350 fits
[CV 8/10] END ..................n_components=1;, score=-0.568 total time=   0.1s
[CV 7/10] END ..................n_components=1;, score=-0.560 total time=   0.1s[CV 9/10] END ..................n_components=1;, score=-0.541 total time=   0.1s

[CV 1/10] END ..................n_components=2;, score=-0.563 total time=   0.1s
[CV 1/10] END ..................n_components=1;, score=-0.565 total time=   0.1s
[CV 6/10] END ..................n_components=1;, score=-0.562 total time=   0.1s
[CV 5/10] END ..................n_components=1;, score=-0.568 total time=   0.1s
[CV 4/10] END ..................n_components=1;, score=-0.562 total time=   0.1s
[CV 2/10] END ..................n_components=1;, score=-0.557 total time=   0.1s
[CV 3/10] END ..................n_components=1;, score=-0.576 total time=   0.1s
[CV 10/10] END .................n_components=1;, score=-0.573 total time=   0.1s
[CV 2/10] END ..................n_components=2;, score=-0.556 total time=   0.1s
[CV 3/10] END ..................n_components=2;, score=-0.573 total time=   0.1s
[CV 4/10] END ..................n_components=2;, score=-0.560 total time=   0.1s
[CV 6/10] END ..................n_components=2;, score=-0.560 total time=   0.0s
[CV 7/10] END ..................n_components=2;, score=-0.558 total time=   0.0s
[CV 3/10] END ..................n_components=3;, score=-0.573 total time=   0.0s
[CV 4/10] END ..................n_components=3;, score=-0.561 total time=   0.0s
[CV 8/10] END ..................n_components=2;, score=-0.566 total time=   0.0s
[CV 5/10] END ..................n_components=3;, score=-0.564 total time=   0.0s
[CV 5/10] END ..................n_components=2;, score=-0.565 total time=   0.1s
[CV 9/10] END ..................n_components=2;, score=-0.538 total time=   0.0s
[CV 10/10] END .................n_components=2;, score=-0.570 total time=   0.0s
[CV 6/10] END ..................n_components=3;, score=-0.560 total time=   0.0s
[CV 1/10] END ..................n_components=3;, score=-0.562 total time=   0.0s
[CV 7/10] END ..................n_components=3;, score=-0.560 total time=   0.0s
[CV 2/10] END ..................n_components=3;, score=-0.555 total time=   0.0s
[CV 8/10] END ..................n_components=3;, score=-0.566 total time=   0.0s
[CV 9/10] END ..................n_components=3;, score=-0.537 total time=   0.0s
[CV 10/10] END .................n_components=3;, score=-0.569 total time=   0.0s
[CV 5/10] END ..................n_components=4;, score=-0.564 total time=   0.0s
[CV 6/10] END ..................n_components=4;, score=-0.560 total time=   0.0s
[CV 7/10] END ..................n_components=4;, score=-0.560 total time=   0.0s
[CV 8/10] END ..................n_components=4;, score=-0.566 total time=   0.0s
[CV 9/10] END ..................n_components=4;, score=-0.536 total time=   0.0s
[CV 1/10] END ..................n_components=4;, score=-0.562 total time=   0.0s
[CV 4/10] END ..................n_components=4;, score=-0.560 total time=   0.0s
[CV 2/10] END ..................n_components=4;, score=-0.555 total time=   0.0s
[CV 10/10] END .................n_components=4;, score=-0.569 total time=   0.0s
[CV 3/10] END ..................n_components=4;, score=-0.573 total time=   0.0s
[CV 1/10] END ..................n_components=5;, score=-0.562 total time=   0.0s
[CV 2/10] END ..................n_components=5;, score=-0.555 total time=   0.0s
[CV 3/10] END ..................n_components=5;, score=-0.573 total time=   0.0s
[CV 4/10] END ..................n_components=5;, score=-0.560 total time=   0.0s
[CV 5/10] END ..................n_components=5;, score=-0.564 total time=   0.0s
[CV 6/10] END ..................n_components=5;, score=-0.560 total time=   0.0s
[CV 8/10] END ..................n_components=5;, score=-0.566 total time=   0.0s
[CV 8/10] END ..................n_components=6;, score=-0.566 total time=   0.0s
[CV 7/10] END ..................n_components=6;, score=-0.560 total time=   0.0s
[CV 6/10] END ..................n_components=6;, score=-0.560 total time=   0.0s
[CV 5/10] END ..................n_components=6;, score=-0.564 total time=   0.0s
[CV 4/10] END ..................n_components=6;, score=-0.561 total time=   0.0s
[CV 10/10] END .................n_components=6;, score=-0.569 total time=   0.0s
[CV 9/10] END ..................n_components=6;, score=-0.537 total time=   0.0s
[CV 1/10] END ..................n_components=7;, score=-0.562 total time=   0.0s
[CV 7/10] END ..................n_components=5;, score=-0.560 total time=   0.1s
[CV 9/10] END ..................n_components=5;, score=-0.536 total time=   0.1s
[CV 10/10] END .................n_components=5;, score=-0.569 total time=   0.1s
[CV 2/10] END ..................n_components=6;, score=-0.555 total time=   0.1s
[CV 1/10] END ..................n_components=6;, score=-0.562 total time=   0.1s
[CV 3/10] END ..................n_components=6;, score=-0.573 total time=   0.1s
[CV 2/10] END ..................n_components=7;, score=-0.555 total time=   0.0s
[CV 6/10] END ..................n_components=7;, score=-0.560 total time=   0.0s
[CV 3/10] END ..................n_components=7;, score=-0.573 total time=   0.0s
[CV 4/10] END ..................n_components=7;, score=-0.561 total time=   0.0s
[CV 5/10] END ..................n_components=7;, score=-0.564 total time=   0.0s
[CV 10/10] END .................n_components=7;, score=-0.569 total time=   0.0s
[CV 7/10] END ..................n_components=7;, score=-0.560 total time=   0.0s
[CV 9/10] END ..................n_components=7;, score=-0.537 total time=   0.0s
[CV 10/10] END .................n_components=8;, score=-0.569 total time=   0.0s
[CV 6/10] END ..................n_components=8;, score=-0.560 total time=   0.0s
[CV 3/10] END ..................n_components=8;, score=-0.573 total time=   0.0s
[CV 8/10] END ..................n_components=7;, score=-0.566 total time=   0.1s
[CV 6/10] END ..................n_components=9;, score=-0.560 total time=   0.0s
[CV 1/10] END ..................n_components=9;, score=-0.562 total time=   0.0s
[CV 2/10] END .................n_components=10;, score=-0.555 total time=   0.0s
[CV 1/10] END ..................n_components=8;, score=-0.562 total time=   0.1s
[CV 2/10] END ..................n_components=9;, score=-0.555 total time=   0.0s
[CV 2/10] END ..................n_components=8;, score=-0.555 total time=   0.1s
[CV 8/10] END ..................n_components=8;, score=-0.566 total time=   0.1s
[CV 7/10] END ..................n_components=8;, score=-0.560 total time=   0.0s
[CV 4/10] END ..................n_components=9;, score=-0.561 total time=   0.1s
[CV 10/10] END .................n_components=9;, score=-0.569 total time=   0.1s
[CV 7/10] END ..................n_components=9;, score=-0.560 total time=   0.0s
[CV 4/10] END ..................n_components=8;, score=-0.561 total time=   0.1s
[CV 8/10] END .................n_components=10;, score=-0.566 total time=   0.0s
[CV 5/10] END ..................n_components=8;, score=-0.564 total time=   0.1s
[CV 4/10] END .................n_components=10;, score=-0.561 total time=   0.0s
[CV 3/10] END .................n_components=10;, score=-0.573 total time=   0.0s
[CV 9/10] END ..................n_components=8;, score=-0.537 total time=   0.0s
[CV 8/10] END ..................n_components=9;, score=-0.566 total time=   0.1s
[CV 3/10] END ..................n_components=9;, score=-0.573 total time=   0.0s
[CV 9/10] END .................n_components=10;, score=-0.537 total time=   0.0s
[CV 5/10] END ..................n_components=9;, score=-0.564 total time=   0.0s
[CV 1/10] END .................n_components=10;, score=-0.562 total time=   0.0s
[CV 5/10] END .................n_components=10;, score=-0.564 total time=   0.0s
[CV 4/10] END .................n_components=11;, score=-0.561 total time=   0.0s
[CV 9/10] END ..................n_components=9;, score=-0.537 total time=   0.0s
[CV 8/10] END .................n_components=11;, score=-0.566 total time=   0.0s
[CV 6/10] END .................n_components=11;, score=-0.560 total time=   0.1s
[CV 8/10] END .................n_components=12;, score=-0.566 total time=   0.0s
[CV 5/10] END .................n_components=11;, score=-0.564 total time=   0.0s
[CV 2/10] END .................n_components=13;, score=-0.555 total time=   0.0s
[CV 4/10] END .................n_components=12;, score=-0.561 total time=   0.1s
[CV 6/10] END .................n_components=10;, score=-0.560 total time=   0.1s
[CV 6/10] END .................n_components=12;, score=-0.560 total time=   0.1s
[CV 9/10] END .................n_components=12;, score=-0.537 total time=   0.0s
[CV 10/10] END ................n_components=12;, score=-0.569 total time=   0.1s
[CV 10/10] END ................n_components=10;, score=-0.569 total time=   0.1s
[CV 3/10] END .................n_components=13;, score=-0.573 total time=   0.0s
[CV 7/10] END .................n_components=11;, score=-0.560 total time=   0.0s
[CV 2/10] END .................n_components=11;, score=-0.555 total time=   0.1s
[CV 5/10] END .................n_components=12;, score=-0.564 total time=   0.0s
[CV 10/10] END ................n_components=13;, score=-0.569 total time=   0.0s
[CV 10/10] END ................n_components=11;, score=-0.569 total time=   0.1s
[CV 9/10] END .................n_components=11;, score=-0.537 total time=   0.1s
[CV 8/10] END .................n_components=13;, score=-0.566 total time=   0.1s
[CV 7/10] END .................n_components=12;, score=-0.560 total time=   0.1s
[CV 6/10] END .................n_components=13;, score=-0.560 total time=   0.1s
[CV 1/10] END .................n_components=13;, score=-0.562 total time=   0.1s
[CV 1/10] END .................n_components=14;, score=-0.562 total time=   0.0s
[CV 7/10] END .................n_components=10;, score=-0.560 total time=   0.1s
[CV 4/10] END .................n_components=14;, score=-0.561 total time=   0.0s
[CV 4/10] END .................n_components=13;, score=-0.561 total time=   0.1s
[CV 2/10] END .................n_components=12;, score=-0.555 total time=   0.1s
[CV 2/10] END .................n_components=14;, score=-0.555 total time=   0.1s
[CV 6/10] END .................n_components=14;, score=-0.560 total time=   0.1s
[CV 7/10] END .................n_components=13;, score=-0.560 total time=   0.0s
[CV 9/10] END .................n_components=13;, score=-0.537 total time=   0.0s
[CV 5/10] END .................n_components=14;, score=-0.564 total time=   0.0s
[CV 1/10] END .................n_components=11;, score=-0.562 total time=   0.1s
[CV 2/10] END .................n_components=16;, score=-0.555 total time=   0.0s
[CV 10/10] END ................n_components=14;, score=-0.569 total time=   0.1s
[CV 3/10] END .................n_components=11;, score=-0.573 total time=   0.1s
[CV 3/10] END .................n_components=14;, score=-0.573 total time=   0.1s
[CV 4/10] END .................n_components=15;, score=-0.561 total time=   0.1s
[CV 1/10] END .................n_components=12;, score=-0.562 total time=   0.1s
[CV 8/10] END .................n_components=17;, score=-0.566 total time=   0.0s
[CV 3/10] END .................n_components=16;, score=-0.573 total time=   0.0s
[CV 7/10] END .................n_components=14;, score=-0.560 total time=   0.1s
[CV 3/10] END .................n_components=12;, score=-0.573 total time=   0.1s
[CV 8/10] END .................n_components=15;, score=-0.566 total time=   0.1s
[CV 5/10] END .................n_components=13;, score=-0.564 total time=   0.1s
[CV 10/10] END ................n_components=16;, score=-0.569 total time=   0.1s
[CV 9/10] END .................n_components=17;, score=-0.537 total time=   0.0s
[CV 1/10] END .................n_components=15;, score=-0.562 total time=   0.1s
[CV 4/10] END .................n_components=17;, score=-0.561 total time=   0.1s
[CV 6/10] END .................n_components=16;, score=-0.560 total time=   0.1s
[CV 4/10] END .................n_components=16;, score=-0.561 total time=   0.1s
[CV 8/10] END .................n_components=14;, score=-0.566 total time=   0.1s
[CV 10/10] END ................n_components=17;, score=-0.569 total time=   0.0s
[CV 9/10] END .................n_components=15;, score=-0.537 total time=   0.1s
[CV 2/10] END .................n_components=18;, score=-0.555 total time=   0.1s
[CV 5/10] END .................n_components=15;, score=-0.564 total time=   0.1s
[CV 10/10] END ................n_components=18;, score=-0.569 total time=   0.1s
[CV 1/10] END .................n_components=17;, score=-0.562 total time=   0.1s
[CV 6/10] END .................n_components=18;, score=-0.560 total time=   0.1s
[CV 2/10] END .................n_components=15;, score=-0.555 total time=   0.1s
[CV 1/10] END .................n_components=18;, score=-0.562 total time=   0.0s
[CV 8/10] END .................n_components=19;, score=-0.566 total time=   0.1s
[CV 9/10] END .................n_components=14;, score=-0.537 total time=   0.1s
[CV 2/10] END .................n_components=20;, score=-0.555 total time=   0.1s
[CV 5/10] END .................n_components=17;, score=-0.564 total time=   0.1s
[CV 10/10] END ................n_components=15;, score=-0.569 total time=   0.1s
[CV 5/10] END .................n_components=16;, score=-0.564 total time=   0.1s
[CV 4/10] END .................n_components=19;, score=-0.561 total time=   0.2s
[CV 7/10] END .................n_components=16;, score=-0.560 total time=   0.1s
[CV 6/10] END .................n_components=15;, score=-0.560 total time=   0.1s
[CV 2/10] END .................n_components=17;, score=-0.555 total time=   0.1s
[CV 1/10] END .................n_components=19;, score=-0.562 total time=   0.1s
[CV 9/10] END .................n_components=19;, score=-0.537 total time=   0.1s[CV 3/10] END .................n_components=18;, score=-0.573 total time=   0.1s

[CV 10/10] END ................n_components=20;, score=-0.569 total time=   0.1s
[CV 6/10] END .................n_components=17;, score=-0.560 total time=   0.1s
[CV 7/10] END .................n_components=15;, score=-0.560 total time=   0.0s
[CV 1/10] END .................n_components=16;, score=-0.562 total time=   0.1s
[CV 6/10] END .................n_components=20;, score=-0.560 total time=   0.1s
[CV 3/10] END .................n_components=15;, score=-0.573 total time=   0.1s
[CV 3/10] END .................n_components=20;, score=-0.573 total time=   0.1s
[CV 4/10] END .................n_components=21;, score=-0.561 total time=   0.1s
[CV 7/10] END .................n_components=18;, score=-0.560 total time=   0.2s
[CV 3/10] END .................n_components=17;, score=-0.573 total time=   0.1s
[CV 2/10] END .................n_components=19;, score=-0.555 total time=   0.1s
[CV 7/10] END .................n_components=17;, score=-0.560 total time=   0.1s
[CV 10/10] END ................n_components=19;, score=-0.569 total time=   0.1s
[CV 6/10] END .................n_components=22;, score=-0.560 total time=   0.1s
[CV 1/10] END .................n_components=21;, score=-0.562 total time=   0.1s
[CV 4/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 2/10] END .................n_components=22;, score=-0.555 total time=   0.1s
[CV 5/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 5/10] END .................n_components=19;, score=-0.564 total time=   0.2s
[CV 6/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 8/10] END .................n_components=21;, score=-0.566 total time=   0.1s
[CV 4/10] END .................n_components=20;, score=-0.561 total time=   0.1s
[CV 7/10] END .................n_components=20;, score=-0.560 total time=   0.1s
[CV 8/10] END .................n_components=16;, score=-0.566 total time=   0.2s
[CV 7/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 4/10] END .................n_components=18;, score=-0.561 total time=   0.1s
[CV 5/10] END .................n_components=21;, score=-0.564 total time=   0.1s
[CV 3/10] END .................n_components=19;, score=-0.573 total time=   0.1s[CV 8/10] END ....................n_components=23;, score=nan total time=   0.0s

[CV 7/10] END .................n_components=22;, score=-0.560 total time=   0.1s
[CV 9/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 2/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 10/10] END ...................n_components=23;, score=nan total time=   0.0s
[CV 3/10] END .................n_components=22;, score=-0.573 total time=   0.1s
[CV 10/10] END ................n_components=22;, score=-0.569 total time=   0.1s
[CV 3/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 1/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 2/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 3/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 1/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 4/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 2/10] END .................n_components=21;, score=-0.555 total time=   0.1s
[CV 5/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 1/10] END .................n_components=20;, score=-0.562 total time=   0.1s
[CV 8/10] END .................n_components=18;, score=-0.566 total time=   0.1s
[CV 10/10] END ...................n_components=24;, score=nan total time=   0.0s
[CV 6/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 8/10] END .................n_components=20;, score=-0.566 total time=   0.1s[CV 1/10] END ....................n_components=25;, score=nan total time=   0.0s

[CV 5/10] END .................n_components=20;, score=-0.564 total time=   0.1s
[CV 4/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 2/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 7/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 8/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 5/10] END ....................n_components=25;, score=nan total time=   0.0s[CV 6/10] END .................n_components=21;, score=-0.560 total time=   0.1s

[CV 3/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 2/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 6/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 8/10] END ....................n_components=24;, score=nan total time=   0.0s[CV 3/10] END ....................n_components=26;, score=nan total time=   0.0s

[CV 4/10] END .................n_components=22;, score=-0.561 total time=   0.1s[CV 8/10] END .................n_components=22;, score=-0.566 total time=   0.1s

[CV 4/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 7/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 9/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 9/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 5/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 6/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 10/10] END ...................n_components=25;, score=nan total time=   0.0s

/home/irinabu/anaconda3/envs/ukbiobank_py11/lib/python3.11/site-packages/sklearn/model_selection/_search.py:976: UserWarning: One or more of the test scores are non-finite: [-0.56322142 -0.56100257 -0.56068459 -0.56067507 -0.56065977 -0.56070898
 -0.56070173 -0.56070281 -0.56070175 -0.56070179 -0.56070182 -0.56070182
 -0.56070182 -0.56070182 -0.56070182 -0.56070182 -0.56070182 -0.56070182
 -0.56070182 -0.56070182 -0.56070182 -0.56070182         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan]
  warnings.warn(

Fold = 0
----------
MSE =  0.49278475366655955
MAE =  0.5605049371250163
R2 =  0.019600265251767945
Pearson's r =  PearsonRResult(statistic=0.14096037133418854, pvalue=5.843923819802905e-25)
----------
Matching brain data to confounds in amplitudes_21
Matching confounds to amplitudes_21 fold 1
Matching g-factor to amplitudes_21 fold 1
Applying ConfoundRegressor to amplitudes_21 fold 1
Fitting PLS to amplitudes_21 fold 1
Fitting 10 folds for each of 35 candidates, totalling 350 fits
[CV 1/10] END ..................n_components=1;, score=-0.661 total time=   0.0s
[CV 6/10] END ..................n_components=1;, score=-0.664 total time=   0.0s
[CV 2/10] END ..................n_components=1;, score=-0.668 total time=   0.0s
[CV 5/10] END ..................n_components=1;, score=-0.665 total time=   0.0s
[CV 7/10] END ..................n_components=1;, score=-0.679 total time=   0.0s
[CV 8/10] END ..................n_components=1;, score=-0.662 total time=   0.0s
[CV 3/10] END ..................n_components=1;, score=-0.682 total time=   0.0s
[CV 4/10] END ..................n_components=1;, score=-0.675 total time=   0.0s
[CV 9/10] END ..................n_components=1;, score=-0.657 total time=   0.0s[CV 10/10] END .................n_components=1;, score=-0.649 total time=   0.0s

[CV 1/10] END ..................n_components=2;, score=-0.660 total time=   0.0s
[CV 5/10] END ..................n_components=2;, score=-0.664 total time=   0.0s
[CV 2/10] END ..................n_components=2;, score=-0.665 total time=   0.0s
[CV 3/10] END ..................n_components=2;, score=-0.680 total time=   0.0s
[CV 4/10] END ..................n_components=2;, score=-0.676 total time=   0.0s
[CV 6/10] END ..................n_components=2;, score=-0.662 total time=   0.0s
[CV 7/10] END ..................n_components=2;, score=-0.678 total time=   0.0s
[CV 8/10] END ..................n_components=2;, score=-0.664 total time=   0.0s
[CV 9/10] END ..................n_components=2;, score=-0.656 total time=   0.0s
[CV 10/10] END .................n_components=2;, score=-0.648 total time=   0.0s
[CV 6/10] END ..................n_components=3;, score=-0.662 total time=   0.0s
[CV 1/10] END ..................n_components=3;, score=-0.660 total time=   0.0s
[CV 7/10] END ..................n_components=3;, score=-0.678 total time=   0.0s
[CV 10/10] END .................n_components=3;, score=-0.648 total time=   0.0s
[CV 4/10] END ..................n_components=3;, score=-0.675 total time=   0.0s[CV 2/10] END ..................n_components=3;, score=-0.665 total time=   0.0s

[CV 5/10] END ..................n_components=3;, score=-0.664 total time=   0.0s
[CV 9/10] END ..................n_components=3;, score=-0.656 total time=   0.0s
[CV 8/10] END ..................n_components=3;, score=-0.663 total time=   0.0s
[CV 1/10] END ..................n_components=4;, score=-0.660 total time=   0.0s
[CV 3/10] END ..................n_components=3;, score=-0.679 total time=   0.0s
[CV 2/10] END ..................n_components=4;, score=-0.665 total time=   0.0s
[CV 3/10] END ..................n_components=4;, score=-0.679 total time=   0.0s
[CV 4/10] END ..................n_components=4;, score=-0.675 total time=   0.0s
[CV 5/10] END ..................n_components=5;, score=-0.664 total time=   0.0s
[CV 9/10] END ..................n_components=4;, score=-0.656 total time=   0.0s
[CV 5/10] END ..................n_components=4;, score=-0.664 total time=   0.0s
[CV 7/10] END ..................n_components=5;, score=-0.678 total time=   0.0s
[CV 7/10] END ..................n_components=4;, score=-0.678 total time=   0.0s
[CV 3/10] END ..................n_components=5;, score=-0.679 total time=   0.0s
[CV 5/10] END ..................n_components=6;, score=-0.664 total time=   0.0s
[CV 6/10] END ..................n_components=5;, score=-0.662 total time=   0.0s
[CV 8/10] END ..................n_components=5;, score=-0.663 total time=   0.0s
[CV 1/10] END ..................n_components=5;, score=-0.660 total time=   0.0s
[CV 7/10] END ..................n_components=6;, score=-0.678 total time=   0.0s
[CV 6/10] END ..................n_components=6;, score=-0.662 total time=   0.0s
[CV 10/10] END .................n_components=4;, score=-0.648 total time=   0.0s
[CV 3/10] END ..................n_components=6;, score=-0.679 total time=   0.0s[CV 9/10] END ..................n_components=5;, score=-0.656 total time=   0.0s

[CV 6/10] END ..................n_components=4;, score=-0.662 total time=   0.0s
[CV 9/10] END ..................n_components=6;, score=-0.656 total time=   0.0s
[CV 1/10] END ..................n_components=6;, score=-0.660 total time=   0.1s
[CV 8/10] END ..................n_components=6;, score=-0.663 total time=   0.0s
[CV 1/10] END ..................n_components=7;, score=-0.660 total time=   0.0s
[CV 8/10] END ..................n_components=4;, score=-0.663 total time=   0.0s
[CV 3/10] END ..................n_components=7;, score=-0.679 total time=   0.1s
[CV 5/10] END ..................n_components=7;, score=-0.664 total time=   0.0s
[CV 9/10] END ..................n_components=7;, score=-0.656 total time=   0.0s
[CV 2/10] END ..................n_components=5;, score=-0.665 total time=   0.0s
[CV 10/10] END .................n_components=6;, score=-0.648 total time=   0.0s
[CV 4/10] END ..................n_components=5;, score=-0.676 total time=   0.1s
[CV 10/10] END .................n_components=7;, score=-0.648 total time=   0.0s
[CV 6/10] END ..................n_components=7;, score=-0.662 total time=   0.0s
[CV 4/10] END ..................n_components=6;, score=-0.676 total time=   0.0s
[CV 10/10] END .................n_components=5;, score=-0.648 total time=   0.1s
[CV 7/10] END ..................n_components=7;, score=-0.678 total time=   0.1s
[CV 1/10] END ..................n_components=8;, score=-0.660 total time=   0.1s
[CV 5/10] END ..................n_components=9;, score=-0.664 total time=   0.0s
[CV 2/10] END ..................n_components=6;, score=-0.665 total time=   0.1s
[CV 7/10] END ..................n_components=9;, score=-0.678 total time=   0.0s
[CV 4/10] END ..................n_components=7;, score=-0.676 total time=   0.1s
[CV 2/10] END ..................n_components=7;, score=-0.665 total time=   0.1s
[CV 3/10] END ..................n_components=8;, score=-0.679 total time=   0.1s
[CV 1/10] END .................n_components=10;, score=-0.660 total time=   0.0s
[CV 5/10] END ..................n_components=8;, score=-0.664 total time=   0.1s
[CV 7/10] END ..................n_components=8;, score=-0.678 total time=   0.1s
[CV 8/10] END ..................n_components=9;, score=-0.663 total time=   0.0s
[CV 6/10] END ..................n_components=9;, score=-0.662 total time=   0.0s
[CV 8/10] END ..................n_components=7;, score=-0.663 total time=   0.0s
[CV 2/10] END .................n_components=10;, score=-0.665 total time=   0.0s
[CV 1/10] END ..................n_components=9;, score=-0.660 total time=   0.1s
[CV 9/10] END ..................n_components=9;, score=-0.656 total time=   0.1s
[CV 5/10] END .................n_components=10;, score=-0.664 total time=   0.0s
[CV 3/10] END .................n_components=10;, score=-0.679 total time=   0.0s
[CV 9/10] END ..................n_components=8;, score=-0.656 total time=   0.1s
[CV 1/10] END .................n_components=12;, score=-0.660 total time=   0.0s
[CV 2/10] END ..................n_components=8;, score=-0.665 total time=   0.1s[CV 6/10] END .................n_components=10;, score=-0.662 total time=   0.0s

[CV 3/10] END ..................n_components=9;, score=-0.679 total time=   0.1s
[CV 6/10] END ..................n_components=8;, score=-0.662 total time=   0.1s
[CV 4/10] END .................n_components=10;, score=-0.676 total time=   0.0s
[CV 4/10] END ..................n_components=8;, score=-0.676 total time=   0.1s
[CV 8/10] END ..................n_components=8;, score=-0.663 total time=   0.1s
[CV 2/10] END .................n_components=12;, score=-0.665 total time=   0.0s
[CV 7/10] END .................n_components=10;, score=-0.678 total time=   0.0s
[CV 10/10] END .................n_components=9;, score=-0.648 total time=   0.1s
[CV 2/10] END ..................n_components=9;, score=-0.665 total time=   0.1s
[CV 3/10] END .................n_components=11;, score=-0.679 total time=   0.1s
[CV 5/10] END .................n_components=12;, score=-0.664 total time=   0.1s
[CV 7/10] END .................n_components=13;, score=-0.678 total time=   0.0s
[CV 8/10] END .................n_components=10;, score=-0.663 total time=   0.0s
[CV 3/10] END .................n_components=12;, score=-0.679 total time=   0.0s
[CV 9/10] END .................n_components=10;, score=-0.656 total time=   0.1s
[CV 8/10] END .................n_components=13;, score=-0.663 total time=   0.0s
[CV 10/10] END .................n_components=8;, score=-0.648 total time=   0.1s
[CV 4/10] END ..................n_components=9;, score=-0.676 total time=   0.1s
[CV 4/10] END .................n_components=12;, score=-0.676 total time=   0.0s
[CV 9/10] END .................n_components=12;, score=-0.656 total time=   0.1s
[CV 9/10] END .................n_components=14;, score=-0.656 total time=   0.0s
[CV 4/10] END .................n_components=11;, score=-0.676 total time=   0.1s
[CV 7/10] END .................n_components=11;, score=-0.678 total time=   0.1s
[CV 9/10] END .................n_components=13;, score=-0.656 total time=   0.0s
[CV 3/10] END .................n_components=13;, score=-0.679 total time=   0.1s
[CV 6/10] END .................n_components=12;, score=-0.662 total time=   0.1s
[CV 7/10] END .................n_components=15;, score=-0.678 total time=   0.1s
[CV 5/10] END .................n_components=14;, score=-0.664 total time=   0.1s[CV 10/10] END ................n_components=13;, score=-0.648 total time=   0.0s

[CV 1/10] END .................n_components=14;, score=-0.660 total time=   0.1s
[CV 10/10] END ................n_components=14;, score=-0.648 total time=   0.1s
[CV 5/10] END .................n_components=16;, score=-0.664 total time=   0.1s
[CV 3/10] END .................n_components=15;, score=-0.679 total time=   0.1s
[CV 10/10] END ................n_components=10;, score=-0.648 total time=   0.1s
[CV 10/10] END ................n_components=12;, score=-0.648 total time=   0.1s
[CV 5/10] END .................n_components=11;, score=-0.664 total time=   0.1s
[CV 3/10] END .................n_components=17;, score=-0.679 total time=   0.0s
[CV 1/10] END .................n_components=15;, score=-0.660 total time=   0.0s
[CV 1/10] END .................n_components=16;, score=-0.660 total time=   0.1s
[CV 4/10] END .................n_components=17;, score=-0.676 total time=   0.0s
[CV 4/10] END .................n_components=13;, score=-0.676 total time=   0.1s
[CV 6/10] END .................n_components=14;, score=-0.662 total time=   0.1s
[CV 7/10] END .................n_components=12;, score=-0.678 total time=   0.1s
[CV 1/10] END .................n_components=13;, score=-0.660 total time=   0.1s
[CV 2/10] END .................n_components=15;, score=-0.665 total time=   0.0s
[CV 8/10] END .................n_components=15;, score=-0.663 total time=   0.1s
[CV 2/10] END .................n_components=14;, score=-0.665 total time=   0.1s[CV 5/10] END .................n_components=17;, score=-0.664 total time=   0.0s

[CV 4/10] END .................n_components=15;, score=-0.676 total time=   0.1s
[CV 1/10] END .................n_components=11;, score=-0.660 total time=   0.1s
[CV 9/10] END .................n_components=16;, score=-0.656 total time=   0.1s
[CV 6/10] END .................n_components=16;, score=-0.662 total time=   0.1s
[CV 6/10] END .................n_components=11;, score=-0.662 total time=   0.1s
[CV 8/10] END .................n_components=11;, score=-0.663 total time=   0.2s
[CV 6/10] END .................n_components=17;, score=-0.662 total time=   0.0s
[CV 9/10] END .................n_components=15;, score=-0.656 total time=   0.1s
[CV 7/10] END .................n_components=16;, score=-0.678 total time=   0.0s[CV 7/10] END .................n_components=17;, score=-0.678 total time=   0.1s

[CV 8/10] END .................n_components=12;, score=-0.663 total time=   0.1s
[CV 7/10] END .................n_components=14;, score=-0.678 total time=   0.1s
[CV 2/10] END .................n_components=16;, score=-0.665 total time=   0.1s
[CV 5/10] END .................n_components=13;, score=-0.664 total time=   0.1s
[CV 2/10] END .................n_components=13;, score=-0.665 total time=   0.1s
[CV 5/10] END .................n_components=18;, score=-0.664 total time=   0.0s
[CV 8/10] END .................n_components=16;, score=-0.663 total time=   0.0s
[CV 5/10] END .................n_components=15;, score=-0.664 total time=   0.1s
[CV 6/10] END .................n_components=18;, score=-0.662 total time=   0.0s
[CV 10/10] END ................n_components=15;, score=-0.648 total time=   0.1s
[CV 8/10] END .................n_components=17;, score=-0.663 total time=   0.1s
[CV 10/10] END ................n_components=16;, score=-0.648 total time=   0.1s
[CV 3/10] END .................n_components=14;, score=-0.679 total time=   0.1s
[CV 2/10] END .................n_components=11;, score=-0.665 total time=   0.1s
[CV 1/10] END .................n_components=18;, score=-0.660 total time=   0.1s
[CV 8/10] END .................n_components=14;, score=-0.663 total time=   0.1s
[CV 7/10] END .................n_components=18;, score=-0.678 total time=   0.0s
[CV 6/10] END .................n_components=13;, score=-0.662 total time=   0.1s
[CV 9/10] END .................n_components=17;, score=-0.656 total time=   0.0s
[CV 8/10] END .................n_components=18;, score=-0.663 total time=   0.0s
[CV 3/10] END .................n_components=19;, score=-0.679 total time=   0.1s
[CV 9/10] END .................n_components=18;, score=-0.656 total time=   0.1s
[CV 9/10] END .................n_components=11;, score=-0.656 total time=   0.2s
[CV 6/10] END .................n_components=15;, score=-0.662 total time=   0.1s
[CV 3/10] END .................n_components=16;, score=-0.679 total time=   0.2s
[CV 4/10] END .................n_components=14;, score=-0.676 total time=   0.1s
[CV 7/10] END .................n_components=19;, score=-0.678 total time=   0.1s
[CV 10/10] END ................n_components=17;, score=-0.648 total time=   0.1s
[CV 7/10] END .................n_components=21;, score=-0.678 total time=   0.0s
[CV 1/10] END .................n_components=17;, score=-0.660 total time=   0.1s
[CV 1/10] END .................n_components=20;, score=-0.660 total time=   0.1s
[CV 7/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 8/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 9/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 2/10] END .................n_components=18;, score=-0.665 total time=   0.1s
[CV 10/10] END ...................n_components=23;, score=nan total time=   0.0s
[CV 1/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 10/10] END ................n_components=18;, score=-0.648 total time=   0.1s
[CV 2/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 3/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 8/10] END .................n_components=19;, score=-0.663 total time=   0.0s
[CV 4/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 9/10] END .................n_components=20;, score=-0.656 total time=   0.1s
[CV 8/10] END .................n_components=21;, score=-0.663 total time=   0.0s
[CV 5/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 6/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 7/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 8/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 9/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 10/10] END ...................n_components=24;, score=nan total time=   0.0s
[CV 1/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 1/10] END .................n_components=19;, score=-0.660 total time=   0.0s
[CV 2/10] END ....................n_components=25;, score=nan total time=   0.0s[CV 2/10] END .................n_components=20;, score=-0.665 total time=   0.1s

[CV 9/10] END .................n_components=19;, score=-0.656 total time=   0.0s
[CV 4/10] END .................n_components=19;, score=-0.676 total time=   0.1s
[CV 9/10] END .................n_components=21;, score=-0.656 total time=   0.0s
[CV 4/10] END .................n_components=16;, score=-0.676 total time=   0.1s
[CV 3/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 5/10] END .................n_components=20;, score=-0.664 total time=   0.2s
[CV 4/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 1/10] END .................n_components=22;, score=-0.660 total time=   0.1s
[CV 10/10] END ................n_components=11;, score=-0.648 total time=   0.2s
[CV 5/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 2/10] END .................n_components=19;, score=-0.665 total time=   0.0s
[CV 2/10] END .................n_components=17;, score=-0.665 total time=   0.1s
[CV 3/10] END .................n_components=21;, score=-0.679 total time=   0.2s
[CV 1/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 10/10] END ................n_components=19;, score=-0.648 total time=   0.0s
[CV 6/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 3/10] END .................n_components=20;, score=-0.679 total time=   0.0s
[CV 3/10] END .................n_components=18;, score=-0.679 total time=   0.1s
[CV 7/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 2/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 10/10] END ................n_components=20;, score=-0.648 total time=   0.1s
[CV 7/10] END ....................n_components=27;, score=nan total time=   0.0s
[CV 10/10] END ................n_components=21;, score=-0.648 total time=   0.0s
[CV 8/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 9/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 5/10] END ....................n_components=28;, score=nan total time=   0.0s[CV 8/10] END ....................n_components=27;, score=nan total time=   0.0s

[CV 6/10] END ....................n_components=28;, score=nan total time=   0.0s
[CV 9/10] END ....................n_components=27;, score=nan total time=   0.0s
[CV 3/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 3/10] END ....................n_components=29;, score=nan total time=   0.0s[CV 10/10] END ...................n_components=27;, score=nan total time=   0.0s[CV 7/10] END ....................n_components=28;, score=nan total time=   0.0s


[CV 9/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 8/10] END ....................n_components=28;, score=nan total time=   0.0s
[CV 9/10] END ....................n_components=28;, score=nan total time=   0.0s
[CV 1/10] END ....................n_components=28;, score=nan total time=   0.0s
[CV 10/10] END ...................n_components=28;, score=nan total time=   0.0s
[CV 10/10] END ...................n_components=26;, score=nan total time=   0.0s
[CV 4/10] END ....................n_components=29;, score=nan total time=   0.0s

/home/irinabu/anaconda3/envs/ukbiobank_py11/lib/python3.11/site-packages/sklearn/model_selection/_search.py:976: UserWarning: One or more of the test scores are non-finite: [-0.66633082 -0.66530553 -0.66503037 -0.66505418 -0.66507967 -0.66511321
 -0.66511251 -0.66510495 -0.66510336 -0.66510319 -0.66510317 -0.66510316
 -0.66510316 -0.66510316 -0.66510316 -0.66510316 -0.66510316 -0.66510316
 -0.66510316 -0.66510316 -0.66510316 -0.66510316         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan]
  warnings.warn(

Fold = 1
----------
MSE =  0.6876849658433719
MAE =  0.6606863302671802
R2 =  0.0023987943096756004
Pearson's r =  PearsonRResult(statistic=0.0645637286985096, pvalue=2.505758331891441e-06)
----------
Matching brain data to confounds in amplitudes_21
Matching confounds to amplitudes_21 fold 2
Matching g-factor to amplitudes_21 fold 2
Applying ConfoundRegressor to amplitudes_21 fold 2
Fitting PLS to amplitudes_21 fold 2
Fitting 10 folds for each of 35 candidates, totalling 350 fits
[CV 3/10] END ..................n_components=1;, score=-0.675 total time=   0.0s
[CV 4/10] END ..................n_components=1;, score=-0.692 total time=   0.0s
[CV 7/10] END ..................n_components=1;, score=-0.699 total time=   0.0s
[CV 1/10] END ..................n_components=1;, score=-0.681 total time=   0.0s
[CV 6/10] END ..................n_components=1;, score=-0.688 total time=   0.0s
[CV 2/10] END ..................n_components=1;, score=-0.694 total time=   0.0s
[CV 8/10] END ..................n_components=1;, score=-0.693 total time=   0.0s
[CV 9/10] END ..................n_components=1;, score=-0.701 total time=   0.0s
[CV 10/10] END .................n_components=1;, score=-0.697 total time=   0.0s
[CV 5/10] END ..................n_components=1;, score=-0.687 total time=   0.0s
[CV 1/10] END ..................n_components=2;, score=-0.682 total time=   0.0s
[CV 3/10] END ..................n_components=2;, score=-0.674 total time=   0.0s
[CV 2/10] END ..................n_components=2;, score=-0.694 total time=   0.0s
[CV 4/10] END ..................n_components=2;, score=-0.690 total time=   0.0s
[CV 5/10] END ..................n_components=2;, score=-0.685 total time=   0.0s
[CV 6/10] END ..................n_components=2;, score=-0.689 total time=   0.0s
[CV 7/10] END ..................n_components=2;, score=-0.698 total time=   0.0s
[CV 8/10] END ..................n_components=2;, score=-0.692 total time=   0.0s
[CV 4/10] END ..................n_components=3;, score=-0.690 total time=   0.0s[CV 3/10] END ..................n_components=3;, score=-0.674 total time=   0.0s

[CV 7/10] END ..................n_components=3;, score=-0.699 total time=   0.0s
[CV 9/10] END ..................n_components=2;, score=-0.701 total time=   0.0s
[CV 10/10] END .................n_components=2;, score=-0.695 total time=   0.0s
[CV 9/10] END ..................n_components=3;, score=-0.700 total time=   0.0s
[CV 2/10] END ..................n_components=3;, score=-0.694 total time=   0.0s
[CV 1/10] END ..................n_components=3;, score=-0.682 total time=   0.0s
[CV 10/10] END .................n_components=3;, score=-0.694 total time=   0.0s
[CV 6/10] END ..................n_components=3;, score=-0.688 total time=   0.0s
[CV 8/10] END ..................n_components=3;, score=-0.691 total time=   0.0s
[CV 5/10] END ..................n_components=3;, score=-0.685 total time=   0.0s
[CV 9/10] END ..................n_components=4;, score=-0.700 total time=   0.0s
[CV 3/10] END ..................n_components=4;, score=-0.674 total time=   0.0s
[CV 5/10] END ..................n_components=4;, score=-0.685 total time=   0.0s
[CV 1/10] END ..................n_components=4;, score=-0.682 total time=   0.0s
[CV 1/10] END ..................n_components=5;, score=-0.682 total time=   0.0s
[CV 7/10] END ..................n_components=4;, score=-0.699 total time=   0.0s
[CV 3/10] END ..................n_components=5;, score=-0.674 total time=   0.0s
[CV 5/10] END ..................n_components=5;, score=-0.685 total time=   0.0s
[CV 10/10] END .................n_components=4;, score=-0.694 total time=   0.0s
[CV 9/10] END ..................n_components=5;, score=-0.700 total time=   0.0s
[CV 7/10] END ..................n_components=5;, score=-0.699 total time=   0.0s
[CV 2/10] END ..................n_components=5;, score=-0.694 total time=   0.0s
[CV 4/10] END ..................n_components=4;, score=-0.691 total time=   0.0s
[CV 6/10] END ..................n_components=4;, score=-0.688 total time=   0.0s
[CV 3/10] END ..................n_components=6;, score=-0.674 total time=   0.0s
[CV 4/10] END ..................n_components=5;, score=-0.691 total time=   0.0s
[CV 10/10] END .................n_components=5;, score=-0.695 total time=   0.0s
[CV 5/10] END ..................n_components=6;, score=-0.685 total time=   0.0s
[CV 8/10] END ..................n_components=4;, score=-0.691 total time=   0.0s
[CV 1/10] END ..................n_components=6;, score=-0.682 total time=   0.0s
[CV 6/10] END ..................n_components=5;, score=-0.688 total time=   0.0s
[CV 8/10] END ..................n_components=5;, score=-0.691 total time=   0.0s
[CV 2/10] END ..................n_components=4;, score=-0.694 total time=   0.0s
[CV 1/10] END ..................n_components=7;, score=-0.682 total time=   0.0s
[CV 4/10] END ..................n_components=6;, score=-0.691 total time=   0.0s
[CV 7/10] END ..................n_components=6;, score=-0.699 total time=   0.1s
[CV 9/10] END ..................n_components=6;, score=-0.700 total time=   0.1s
[CV 6/10] END ..................n_components=6;, score=-0.687 total time=   0.0s
[CV 1/10] END ..................n_components=8;, score=-0.682 total time=   0.0s
[CV 5/10] END ..................n_components=7;, score=-0.685 total time=   0.0s
[CV 2/10] END ..................n_components=7;, score=-0.694 total time=   0.0s
[CV 7/10] END ..................n_components=7;, score=-0.699 total time=   0.0s
[CV 7/10] END ..................n_components=8;, score=-0.699 total time=   0.0s
[CV 2/10] END ..................n_components=6;, score=-0.694 total time=   0.0s
[CV 9/10] END ..................n_components=7;, score=-0.700 total time=   0.0s
[CV 3/10] END ..................n_components=8;, score=-0.674 total time=   0.0s
[CV 2/10] END ..................n_components=8;, score=-0.694 total time=   0.0s
[CV 1/10] END ..................n_components=9;, score=-0.682 total time=   0.0s
[CV 8/10] END ..................n_components=8;, score=-0.691 total time=   0.0s
[CV 10/10] END .................n_components=6;, score=-0.695 total time=   0.0s[CV 8/10] END ..................n_components=6;, score=-0.691 total time=   0.0s

[CV 6/10] END ..................n_components=7;, score=-0.687 total time=   0.0s
[CV 5/10] END ..................n_components=9;, score=-0.685 total time=   0.0s
[CV 4/10] END ..................n_components=8;, score=-0.691 total time=   0.0s
[CV 8/10] END ..................n_components=7;, score=-0.691 total time=   0.0s
[CV 10/10] END .................n_components=7;, score=-0.695 total time=   0.0s
[CV 5/10] END ..................n_components=8;, score=-0.685 total time=   0.1s
[CV 3/10] END ..................n_components=7;, score=-0.674 total time=   0.1s
[CV 3/10] END ..................n_components=9;, score=-0.674 total time=   0.1s
[CV 9/10] END ..................n_components=9;, score=-0.700 total time=   0.0s
[CV 1/10] END .................n_components=10;, score=-0.682 total time=   0.0s
[CV 2/10] END ..................n_components=9;, score=-0.694 total time=   0.0s
[CV 9/10] END ..................n_components=8;, score=-0.700 total time=   0.1s
[CV 7/10] END ..................n_components=9;, score=-0.699 total time=   0.1s
[CV 6/10] END ..................n_components=9;, score=-0.687 total time=   0.0s
[CV 10/10] END .................n_components=9;, score=-0.695 total time=   0.0s
[CV 2/10] END .................n_components=10;, score=-0.694 total time=   0.0s
[CV 7/10] END .................n_components=11;, score=-0.699 total time=   0.0s
[CV 5/10] END .................n_components=10;, score=-0.685 total time=   0.1s[CV 4/10] END ..................n_components=7;, score=-0.691 total time=   0.0s

[CV 6/10] END ..................n_components=8;, score=-0.687 total time=   0.1s
[CV 4/10] END ..................n_components=9;, score=-0.691 total time=   0.1s
[CV 9/10] END .................n_components=12;, score=-0.700 total time=   0.0s
[CV 8/10] END .................n_components=11;, score=-0.691 total time=   0.0s
[CV 10/10] END .................n_components=8;, score=-0.695 total time=   0.1s
[CV 9/10] END .................n_components=10;, score=-0.700 total time=   0.1s[CV 8/10] END ..................n_components=9;, score=-0.691 total time=   0.1s

[CV 3/10] END .................n_components=10;, score=-0.674 total time=   0.0s
[CV 3/10] END .................n_components=13;, score=-0.674 total time=   0.1s
[CV 3/10] END .................n_components=11;, score=-0.674 total time=   0.1s
[CV 6/10] END .................n_components=10;, score=-0.687 total time=   0.0s
[CV 9/10] END .................n_components=11;, score=-0.700 total time=   0.0s[CV 5/10] END .................n_components=12;, score=-0.685 total time=   0.1s

[CV 1/10] END .................n_components=12;, score=-0.682 total time=   0.1s
[CV 1/10] END .................n_components=14;, score=-0.682 total time=   0.1s
[CV 4/10] END .................n_components=10;, score=-0.691 total time=   0.0s
[CV 10/10] END ................n_components=11;, score=-0.695 total time=   0.0s
[CV 10/10] END ................n_components=10;, score=-0.695 total time=   0.1s
[CV 4/10] END .................n_components=13;, score=-0.691 total time=   0.0s
[CV 6/10] END .................n_components=12;, score=-0.687 total time=   0.0s
[CV 7/10] END .................n_components=10;, score=-0.699 total time=   0.0s
[CV 4/10] END .................n_components=11;, score=-0.691 total time=   0.1s
[CV 9/10] END .................n_components=14;, score=-0.700 total time=   0.1s
[CV 7/10] END .................n_components=12;, score=-0.699 total time=   0.0s
[CV 3/10] END .................n_components=15;, score=-0.674 total time=   0.1s
[CV 2/10] END .................n_components=14;, score=-0.694 total time=   0.0s
[CV 1/10] END .................n_components=16;, score=-0.682 total time=   0.0s
[CV 7/10] END .................n_components=15;, score=-0.699 total time=   0.1s
[CV 10/10] END ................n_components=12;, score=-0.695 total time=   0.1s
[CV 5/10] END .................n_components=13;, score=-0.685 total time=   0.0s
[CV 5/10] END .................n_components=14;, score=-0.685 total time=   0.1s
[CV 8/10] END .................n_components=10;, score=-0.691 total time=   0.0s
[CV 7/10] END .................n_components=13;, score=-0.699 total time=   0.1s
[CV 1/10] END .................n_components=11;, score=-0.682 total time=   0.1s
[CV 8/10] END .................n_components=12;, score=-0.691 total time=   0.0s
[CV 5/10] END .................n_components=16;, score=-0.685 total time=   0.1s
[CV 5/10] END .................n_components=11;, score=-0.685 total time=   0.1s
[CV 2/10] END .................n_components=16;, score=-0.694 total time=   0.0s
[CV 6/10] END .................n_components=13;, score=-0.687 total time=   0.0s
[CV 2/10] END .................n_components=12;, score=-0.694 total time=   0.1s[CV 3/10] END .................n_components=14;, score=-0.674 total time=   0.1s

[CV 10/10] END ................n_components=14;, score=-0.695 total time=   0.1s
[CV 9/10] END .................n_components=16;, score=-0.700 total time=   0.1s[CV 2/10] END .................n_components=11;, score=-0.694 total time=   0.1s

[CV 3/10] END .................n_components=16;, score=-0.674 total time=   0.0s
[CV 4/10] END .................n_components=15;, score=-0.691 total time=   0.1s
[CV 6/10] END .................n_components=16;, score=-0.687 total time=   0.1s
[CV 8/10] END .................n_components=15;, score=-0.691 total time=   0.1s
[CV 4/10] END .................n_components=14;, score=-0.691 total time=   0.1s
[CV 6/10] END .................n_components=11;, score=-0.687 total time=   0.1s
[CV 4/10] END .................n_components=16;, score=-0.691 total time=   0.0s
[CV 6/10] END .................n_components=14;, score=-0.687 total time=   0.1s
[CV 7/10] END .................n_components=16;, score=-0.699 total time=   0.1s
[CV 3/10] END .................n_components=17;, score=-0.674 total time=   0.1s
[CV 7/10] END .................n_components=17;, score=-0.699 total time=   0.1s
[CV 10/10] END ................n_components=16;, score=-0.695 total time=   0.1s
[CV 3/10] END .................n_components=12;, score=-0.674 total time=   0.1s
[CV 1/10] END .................n_components=15;, score=-0.682 total time=   0.1s
[CV 5/10] END .................n_components=15;, score=-0.685 total time=   0.1s
[CV 1/10] END .................n_components=13;, score=-0.682 total time=   0.2s
[CV 9/10] END .................n_components=15;, score=-0.700 total time=   0.1s
[CV 5/10] END .................n_components=18;, score=-0.685 total time=   0.1s
[CV 1/10] END .................n_components=18;, score=-0.682 total time=   0.1s
[CV 8/10] END .................n_components=17;, score=-0.691 total time=   0.1s
[CV 8/10] END .................n_components=13;, score=-0.691 total time=   0.2s
[CV 8/10] END .................n_components=16;, score=-0.691 total time=   0.1s
[CV 7/10] END .................n_components=14;, score=-0.699 total time=   0.1s
[CV 6/10] END .................n_components=18;, score=-0.687 total time=   0.1s
[CV 2/10] END .................n_components=15;, score=-0.694 total time=   0.1s
[CV 4/10] END .................n_components=12;, score=-0.691 total time=   0.1s
[CV 6/10] END .................n_components=15;, score=-0.687 total time=   0.1s
[CV 1/10] END .................n_components=17;, score=-0.682 total time=   0.1s
[CV 3/10] END .................n_components=19;, score=-0.674 total time=   0.1s
[CV 9/10] END .................n_components=13;, score=-0.700 total time=   0.1s
[CV 10/10] END ................n_components=15;, score=-0.695 total time=   0.1s
[CV 9/10] END .................n_components=18;, score=-0.700 total time=   0.2s
[CV 4/10] END .................n_components=17;, score=-0.691 total time=   0.1s
[CV 9/10] END .................n_components=17;, score=-0.700 total time=   0.1s
[CV 2/10] END .................n_components=13;, score=-0.694 total time=   0.1s
[CV 2/10] END .................n_components=18;, score=-0.694 total time=   0.1s
[CV 7/10] END .................n_components=19;, score=-0.699 total time=   0.1s
[CV 7/10] END .................n_components=18;, score=-0.699 total time=   0.1s
[CV 10/10] END ................n_components=13;, score=-0.695 total time=   0.1s
[CV 1/10] END .................n_components=20;, score=-0.682 total time=   0.1s
[CV 2/10] END .................n_components=17;, score=-0.694 total time=   0.1s
[CV 8/10] END .................n_components=14;, score=-0.691 total time=   0.1s
[CV 5/10] END .................n_components=17;, score=-0.685 total time=   0.1s
[CV 4/10] END .................n_components=19;, score=-0.691 total time=   0.1s
[CV 1/10] END .................n_components=22;, score=-0.682 total time=   0.0s
[CV 10/10] END ................n_components=17;, score=-0.695 total time=   0.1s
[CV 8/10] END .................n_components=18;, score=-0.691 total time=   0.1s
[CV 8/10] END .................n_components=19;, score=-0.691 total time=   0.1s
[CV 2/10] END .................n_components=20;, score=-0.694 total time=   0.1s
[CV 3/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 7/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 4/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 9/10] END .................n_components=20;, score=-0.700 total time=   0.1s
[CV 5/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 8/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 6/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 9/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 3/10] END .................n_components=18;, score=-0.674 total time=   0.1s
[CV 10/10] END ................n_components=18;, score=-0.695 total time=   0.1s
[CV 6/10] END .................n_components=17;, score=-0.687 total time=   0.1s
[CV 10/10] END ...................n_components=23;, score=nan total time=   0.0s
[CV 1/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 2/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 5/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 3/10] END .................n_components=21;, score=-0.674 total time=   0.2s
[CV 3/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 4/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 6/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 9/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 9/10] END .................n_components=19;, score=-0.700 total time=   0.1s
[CV 5/10] END .................n_components=22;, score=-0.685 total time=   0.1s
[CV 2/10] END .................n_components=22;, score=-0.694 total time=   0.1s
[CV 7/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 3/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 5/10] END .................n_components=19;, score=-0.685 total time=   0.1s
[CV 10/10] END ...................n_components=24;, score=nan total time=   0.0s
[CV 4/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 7/10] END .................n_components=21;, score=-0.699 total time=   0.2s
[CV 8/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 5/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 6/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 3/10] END .................n_components=20;, score=-0.674 total time=   0.1s
[CV 1/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 5/10] END .................n_components=20;, score=-0.685 total time=   0.2s
[CV 7/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 1/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 2/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 2/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 8/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 3/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 4/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 9/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 5/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 10/10] END ...................n_components=25;, score=nan total time=   0.0s
[CV 9/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 10/10] END ...................n_components=26;, score=nan total time=   0.0s
[CV 6/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 10/10] END ................n_components=19;, score=-0.695 total time=   0.1s
[CV 1/10] END ....................n_components=27;, score=nan total time=   0.0s
[CV 3/10] END ....................n_components=27;, score=nan total time=   0.0s
[CV 2/10] END ....................n_components=27;, score=nan total time=   0.0s
[CV 7/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 4/10] END .................n_components=18;, score=-0.691 total time=   0.1s
[CV 7/10] END ....................n_components=27;, score=nan total time=   0.0s
[CV 10/10] END ................n_components=20;, score=-0.695 total time=   0.1s
[CV 4/10] END ....................n_components=27;, score=nan total time=   0.0s

/home/irinabu/anaconda3/envs/ukbiobank_py11/lib/python3.11/site-packages/sklearn/model_selection/_search.py:976: UserWarning: One or more of the test scores are non-finite: [-0.69063329 -0.6899109  -0.68971105 -0.68970784 -0.68968731 -0.68971278
 -0.68970211 -0.68970216 -0.68970103 -0.68970116 -0.68970122 -0.68970122
 -0.68970122 -0.68970122 -0.68970122 -0.68970122 -0.68970122 -0.68970122
 -0.68970122 -0.68970122 -0.68970122 -0.68970122         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan]
  warnings.warn(

Predicting & saving g_train for amplitudes_21 fold 2
Fold = 2
----------
MSE =  0.7756488482106038
MAE =  0.7057945164220235
R2 =  0.007032601336971589
Pearson's r =  PearsonRResult(statistic=0.08507486909788564, pvalue=4.693016881070875e-10)
----------
Matching brain data to confounds in amplitudes_21
Matching confounds to amplitudes_21 fold 3
Matching g-factor to amplitudes_21 fold 3
Applying ConfoundRegressor to amplitudes_21 fold 3
Fitting PLS to amplitudes_21 fold 3
Fitting 10 folds for each of 35 candidates, totalling 350 fits
[CV 4/10] END ..................n_components=1;, score=-0.577 total time=   0.0s
[CV 3/10] END ..................n_components=1;, score=-0.582 total time=   0.0s
[CV 1/10] END ..................n_components=1;, score=-0.565 total time=   0.0s
[CV 9/10] END ..................n_components=1;, score=-0.571 total time=   0.0s
[CV 2/10] END ..................n_components=1;, score=-0.572 total time=   0.0s
[CV 5/10] END ..................n_components=1;, score=-0.563 total time=   0.0s
[CV 6/10] END ..................n_components=1;, score=-0.565 total time=   0.0s
[CV 7/10] END ..................n_components=1;, score=-0.583 total time=   0.0s
[CV 10/10] END .................n_components=1;, score=-0.562 total time=   0.0s
[CV 2/10] END ..................n_components=2;, score=-0.569 total time=   0.0s
[CV 4/10] END ..................n_components=2;, score=-0.574 total time=   0.0s[CV 3/10] END ..................n_components=2;, score=-0.578 total time=   0.0s

[CV 1/10] END ..................n_components=2;, score=-0.565 total time=   0.0s
[CV 8/10] END ..................n_components=1;, score=-0.586 total time=   0.0s
[CV 7/10] END ..................n_components=2;, score=-0.582 total time=   0.0s
[CV 6/10] END ..................n_components=2;, score=-0.563 total time=   0.0s
[CV 8/10] END ..................n_components=2;, score=-0.585 total time=   0.0s
[CV 5/10] END ..................n_components=2;, score=-0.560 total time=   0.0s
[CV 9/10] END ..................n_components=2;, score=-0.569 total time=   0.0s
[CV 10/10] END .................n_components=2;, score=-0.559 total time=   0.0s
[CV 1/10] END ..................n_components=3;, score=-0.566 total time=   0.0s
[CV 4/10] END ..................n_components=3;, score=-0.572 total time=   0.0s
[CV 3/10] END ..................n_components=3;, score=-0.578 total time=   0.0s[CV 2/10] END ..................n_components=3;, score=-0.568 total time=   0.0s

[CV 5/10] END ..................n_components=3;, score=-0.559 total time=   0.0s
[CV 6/10] END ..................n_components=3;, score=-0.563 total time=   0.0s
[CV 7/10] END ..................n_components=3;, score=-0.581 total time=   0.0s
[CV 9/10] END ..................n_components=3;, score=-0.570 total time=   0.0s
[CV 8/10] END ..................n_components=3;, score=-0.585 total time=   0.0s
[CV 10/10] END .................n_components=3;, score=-0.558 total time=   0.0s
[CV 1/10] END ..................n_components=4;, score=-0.565 total time=   0.0s
[CV 5/10] END ..................n_components=4;, score=-0.559 total time=   0.0s
[CV 3/10] END ..................n_components=4;, score=-0.578 total time=   0.0s
[CV 2/10] END ..................n_components=4;, score=-0.568 total time=   0.0s
[CV 7/10] END ..................n_components=4;, score=-0.581 total time=   0.0s
[CV 9/10] END ..................n_components=4;, score=-0.570 total time=   0.0s
[CV 3/10] END ..................n_components=5;, score=-0.578 total time=   0.0s
[CV 6/10] END ..................n_components=4;, score=-0.564 total time=   0.0s
[CV 3/10] END ..................n_components=6;, score=-0.578 total time=   0.0s
[CV 1/10] END ..................n_components=5;, score=-0.565 total time=   0.0s[CV 1/10] END ..................n_components=6;, score=-0.565 total time=   0.0s

[CV 4/10] END ..................n_components=4;, score=-0.572 total time=   0.0s
[CV 9/10] END ..................n_components=5;, score=-0.570 total time=   0.0s
[CV 8/10] END ..................n_components=4;, score=-0.585 total time=   0.0s
[CV 5/10] END ..................n_components=5;, score=-0.559 total time=   0.0s
[CV 9/10] END ..................n_components=6;, score=-0.570 total time=   0.0s
[CV 4/10] END ..................n_components=6;, score=-0.572 total time=   0.0s
[CV 1/10] END ..................n_components=7;, score=-0.565 total time=   0.0s
[CV 10/10] END .................n_components=4;, score=-0.559 total time=   0.0s[CV 7/10] END ..................n_components=5;, score=-0.581 total time=   0.1s

[CV 4/10] END ..................n_components=5;, score=-0.572 total time=   0.0s
[CV 2/10] END ..................n_components=6;, score=-0.568 total time=   0.0s
[CV 5/10] END ..................n_components=6;, score=-0.559 total time=   0.1s
[CV 10/10] END .................n_components=5;, score=-0.559 total time=   0.0s
[CV 10/10] END .................n_components=6;, score=-0.559 total time=   0.0s
[CV 7/10] END ..................n_components=6;, score=-0.581 total time=   0.1s
[CV 2/10] END ..................n_components=5;, score=-0.568 total time=   0.0s
[CV 5/10] END ..................n_components=7;, score=-0.559 total time=   0.0s
[CV 9/10] END ..................n_components=7;, score=-0.570 total time=   0.0s
[CV 2/10] END ..................n_components=7;, score=-0.568 total time=   0.0s
[CV 3/10] END ..................n_components=7;, score=-0.578 total time=   0.1s
[CV 7/10] END ..................n_components=7;, score=-0.581 total time=   0.1s
[CV 8/10] END ..................n_components=5;, score=-0.585 total time=   0.1s
[CV 7/10] END ..................n_components=8;, score=-0.581 total time=   0.0s
[CV 6/10] END ..................n_components=6;, score=-0.564 total time=   0.0s
[CV 8/10] END ..................n_components=6;, score=-0.585 total time=   0.0s[CV 9/10] END ..................n_components=8;, score=-0.570 total time=   0.0s

[CV 1/10] END ..................n_components=8;, score=-0.565 total time=   0.1s
[CV 6/10] END ..................n_components=5;, score=-0.564 total time=   0.1s
[CV 6/10] END ..................n_components=7;, score=-0.564 total time=   0.0s
[CV 8/10] END ..................n_components=8;, score=-0.585 total time=   0.0s
[CV 10/10] END .................n_components=7;, score=-0.559 total time=   0.0s
[CV 4/10] END ..................n_components=7;, score=-0.572 total time=   0.0s
[CV 3/10] END ..................n_components=8;, score=-0.578 total time=   0.1s
[CV 8/10] END ..................n_components=7;, score=-0.585 total time=   0.0s
[CV 3/10] END ..................n_components=9;, score=-0.578 total time=   0.0s
[CV 5/10] END ..................n_components=8;, score=-0.559 total time=   0.1s
[CV 1/10] END ..................n_components=9;, score=-0.565 total time=   0.1s
[CV 10/10] END .................n_components=8;, score=-0.559 total time=   0.1s
[CV 5/10] END ..................n_components=9;, score=-0.559 total time=   0.1s
[CV 3/10] END .................n_components=11;, score=-0.578 total time=   0.0s
[CV 2/10] END ..................n_components=8;, score=-0.568 total time=   0.1s
[CV 7/10] END .................n_components=11;, score=-0.581 total time=   0.0s
[CV 4/10] END ..................n_components=9;, score=-0.572 total time=   0.0s
[CV 4/10] END ..................n_components=8;, score=-0.572 total time=   0.1s
[CV 6/10] END ..................n_components=8;, score=-0.564 total time=   0.0s
[CV 7/10] END ..................n_components=9;, score=-0.581 total time=   0.1s
[CV 1/10] END .................n_components=10;, score=-0.565 total time=   0.1s
[CV 4/10] END .................n_components=11;, score=-0.572 total time=   0.0s
[CV 5/10] END .................n_components=10;, score=-0.559 total time=   0.1s
[CV 8/10] END .................n_components=11;, score=-0.585 total time=   0.0s
[CV 1/10] END .................n_components=12;, score=-0.565 total time=   0.1s
[CV 2/10] END ..................n_components=9;, score=-0.568 total time=   0.1s[CV 5/10] END .................n_components=11;, score=-0.559 total time=   0.0s

[CV 6/10] END ..................n_components=9;, score=-0.564 total time=   0.1s
[CV 5/10] END .................n_components=12;, score=-0.559 total time=   0.1s
[CV 9/10] END ..................n_components=9;, score=-0.570 total time=   0.1s
[CV 9/10] END .................n_components=11;, score=-0.570 total time=   0.0s
[CV 6/10] END .................n_components=11;, score=-0.564 total time=   0.0s
[CV 9/10] END .................n_components=10;, score=-0.570 total time=   0.1s
[CV 9/10] END .................n_components=12;, score=-0.570 total time=   0.1s
[CV 3/10] END .................n_components=13;, score=-0.578 total time=   0.1s
[CV 2/10] END .................n_components=10;, score=-0.568 total time=   0.1s
[CV 8/10] END ..................n_components=9;, score=-0.585 total time=   0.1s
[CV 6/10] END .................n_components=10;, score=-0.564 total time=   0.1s
[CV 10/10] END ................n_components=11;, score=-0.559 total time=   0.0s
[CV 7/10] END .................n_components=13;, score=-0.581 total time=   0.1s
[CV 6/10] END .................n_components=12;, score=-0.564 total time=   0.1s
[CV 3/10] END .................n_components=15;, score=-0.578 total time=   0.0s
[CV 5/10] END .................n_components=14;, score=-0.559 total time=   0.1s
[CV 2/10] END .................n_components=12;, score=-0.568 total time=   0.1s
[CV 1/10] END .................n_components=14;, score=-0.565 total time=   0.1s
[CV 10/10] END .................n_components=9;, score=-0.559 total time=   0.1s
[CV 1/10] END .................n_components=16;, score=-0.565 total time=   0.1s
[CV 4/10] END .................n_components=15;, score=-0.572 total time=   0.0s
[CV 3/10] END .................n_components=10;, score=-0.578 total time=   0.1s
[CV 4/10] END .................n_components=13;, score=-0.572 total time=   0.1s
[CV 10/10] END ................n_components=12;, score=-0.559 total time=   0.1s
[CV 8/10] END .................n_components=13;, score=-0.585 total time=   0.1s
[CV 7/10] END .................n_components=12;, score=-0.581 total time=   0.1s[CV 9/10] END .................n_components=14;, score=-0.570 total time=   0.1s

[CV 5/10] END .................n_components=15;, score=-0.559 total time=   0.0s
[CV 7/10] END .................n_components=10;, score=-0.581 total time=   0.1s
[CV 10/10] END ................n_components=10;, score=-0.559 total time=   0.1s
[CV 6/10] END .................n_components=14;, score=-0.564 total time=   0.1s
[CV 2/10] END .................n_components=16;, score=-0.568 total time=   0.0s
[CV 3/10] END .................n_components=12;, score=-0.578 total time=   0.1s
[CV 7/10] END .................n_components=15;, score=-0.581 total time=   0.1s
[CV 6/10] END .................n_components=15;, score=-0.564 total time=   0.0s
[CV 9/10] END .................n_components=13;, score=-0.570 total time=   0.1s[CV 4/10] END .................n_components=10;, score=-0.572 total time=   0.1s

[CV 5/10] END .................n_components=13;, score=-0.559 total time=   0.1s
[CV 2/10] END .................n_components=14;, score=-0.568 total time=   0.1s
[CV 3/10] END .................n_components=16;, score=-0.578 total time=   0.0s
[CV 1/10] END .................n_components=13;, score=-0.565 total time=   0.1s
[CV 7/10] END .................n_components=14;, score=-0.581 total time=   0.1s
[CV 8/10] END .................n_components=12;, score=-0.585 total time=   0.1s
[CV 9/10] END .................n_components=16;, score=-0.570 total time=   0.0s
[CV 4/10] END .................n_components=12;, score=-0.572 total time=   0.1s
[CV 10/10] END ................n_components=13;, score=-0.559 total time=   0.1s
[CV 4/10] END .................n_components=16;, score=-0.572 total time=   0.1s
[CV 10/10] END ................n_components=14;, score=-0.559 total time=   0.1s
[CV 10/10] END ................n_components=16;, score=-0.559 total time=   0.0s
[CV 6/10] END .................n_components=13;, score=-0.564 total time=   0.1s
[CV 8/10] END .................n_components=14;, score=-0.585 total time=   0.1s[CV 1/10] END .................n_components=11;, score=-0.565 total time=   0.1s

[CV 8/10] END .................n_components=10;, score=-0.585 total time=   0.1s
[CV 3/10] END .................n_components=14;, score=-0.578 total time=   0.1s
[CV 8/10] END .................n_components=15;, score=-0.585 total time=   0.1s
[CV 3/10] END .................n_components=17;, score=-0.578 total time=   0.1s
[CV 1/10] END .................n_components=17;, score=-0.565 total time=   0.0s
[CV 2/10] END .................n_components=13;, score=-0.568 total time=   0.1s[CV 5/10] END .................n_components=18;, score=-0.559 total time=   0.1s

[CV 7/10] END .................n_components=17;, score=-0.581 total time=   0.1s
[CV 5/10] END .................n_components=16;, score=-0.559 total time=   0.2s
[CV 2/10] END .................n_components=17;, score=-0.568 total time=   0.0s
[CV 9/10] END .................n_components=18;, score=-0.570 total time=   0.1s
[CV 1/10] END .................n_components=18;, score=-0.565 total time=   0.1s
[CV 7/10] END .................n_components=19;, score=-0.581 total time=   0.1s
[CV 6/10] END .................n_components=18;, score=-0.564 total time=   0.1s
[CV 3/10] END .................n_components=19;, score=-0.578 total time=   0.1s
[CV 1/10] END .................n_components=15;, score=-0.565 total time=   0.1s
[CV 4/10] END .................n_components=17;, score=-0.572 total time=   0.1s
[CV 2/10] END .................n_components=11;, score=-0.568 total time=   0.1s
[CV 9/10] END .................n_components=15;, score=-0.570 total time=   0.1s
[CV 8/10] END .................n_components=17;, score=-0.585 total time=   0.1s
[CV 4/10] END .................n_components=14;, score=-0.572 total time=   0.1s
[CV 1/10] END .................n_components=20;, score=-0.565 total time=   0.1s
[CV 10/10] END ................n_components=18;, score=-0.559 total time=   0.1s
[CV 7/10] END .................n_components=18;, score=-0.581 total time=   0.1s
[CV 8/10] END .................n_components=19;, score=-0.585 total time=   0.1s
[CV 5/10] END .................n_components=17;, score=-0.559 total time=   0.1s
[CV 4/10] END .................n_components=19;, score=-0.572 total time=   0.1s
[CV 2/10] END .................n_components=20;, score=-0.568 total time=   0.1s
[CV 6/10] END .................n_components=16;, score=-0.564 total time=   0.2s
[CV 9/10] END .................n_components=17;, score=-0.570 total time=   0.1s
[CV 2/10] END .................n_components=15;, score=-0.568 total time=   0.1s
[CV 7/10] END .................n_components=21;, score=-0.581 total time=   0.1s
[CV 9/10] END .................n_components=20;, score=-0.570 total time=   0.2s
[CV 8/10] END .................n_components=18;, score=-0.585 total time=   0.1s
[CV 2/10] END .................n_components=18;, score=-0.568 total time=   0.2s
[CV 10/10] END ................n_components=15;, score=-0.559 total time=   0.1s
[CV 5/10] END .................n_components=20;, score=-0.559 total time=   0.2s
[CV 1/10] END .................n_components=19;, score=-0.565 total time=   0.1s
[CV 9/10] END .................n_components=19;, score=-0.570 total time=   0.1s
[CV 6/10] END .................n_components=17;, score=-0.564 total time=   0.1s
[CV 3/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 4/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 5/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 6/10] END ....................n_components=23;, score=nan total time=   0.0s[CV 3/10] END .................n_components=20;, score=-0.578 total time=   0.1s

[CV 5/10] END .................n_components=22;, score=-0.559 total time=   0.1s
[CV 8/10] END .................n_components=21;, score=-0.585 total time=   0.1s
[CV 5/10] END .................n_components=19;, score=-0.559 total time=   0.1s
[CV 7/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 8/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 9/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 10/10] END ...................n_components=23;, score=nan total time=   0.0s
[CV 1/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 2/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 3/10] END .................n_components=21;, score=-0.578 total time=   0.2s
[CV 3/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 4/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 10/10] END ................n_components=20;, score=-0.559 total time=   0.1s
[CV 6/10] END .................n_components=22;, score=-0.564 total time=   0.1s
[CV 10/10] END ................n_components=17;, score=-0.559 total time=   0.1s
[CV 5/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 6/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 4/10] END .................n_components=20;, score=-0.572 total time=   0.1s
[CV 2/10] END .................n_components=19;, score=-0.568 total time=   0.1s
[CV 7/10] END ....................n_components=24;, score=nan total time=   0.0s[CV 9/10] END .................n_components=21;, score=-0.570 total time=   0.1s

[CV 10/10] END ................n_components=19;, score=-0.559 total time=   0.1s
[CV 9/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 3/10] END .................n_components=18;, score=-0.578 total time=   0.1s
[CV 8/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 10/10] END ...................n_components=24;, score=nan total time=   0.0s
[CV 7/10] END .................n_components=16;, score=-0.581 total time=   0.2s
[CV 3/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 1/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 4/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 2/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 7/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 5/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 6/10] END .................n_components=20;, score=-0.564 total time=   0.1s
[CV 8/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 6/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 9/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 9/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 10/10] END ...................n_components=25;, score=nan total time=   0.0s
[CV 7/10] END .................n_components=22;, score=-0.581 total time=   0.1s
[CV 3/10] END ....................n_components=27;, score=nan total time=   0.0s
[CV 10/10] END ...................n_components=26;, score=nan total time=   0.0s
[CV 6/10] END .................n_components=19;, score=-0.564 total time=   0.1s
[CV 7/10] END ....................n_components=27;, score=nan total time=   0.0s[CV 1/10] END ....................n_components=26;, score=nan total time=   0.0s

[CV 4/10] END ....................n_components=27;, score=nan total time=   0.0s
[CV 5/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 9/10] END .................n_components=22;, score=-0.570 total time=   0.2s
[CV 1/10] END .................n_components=22;, score=-0.565 total time=   0.2s

/home/irinabu/anaconda3/envs/ukbiobank_py11/lib/python3.11/site-packages/sklearn/model_selection/_search.py:976: UserWarning: One or more of the test scores are non-finite: [-0.57259717 -0.57043425 -0.57016157 -0.5701935  -0.57016872 -0.57019551
 -0.57018271 -0.57018029 -0.5701793  -0.5701792  -0.57017924 -0.57017924
 -0.57017925 -0.57017925 -0.57017925 -0.57017925 -0.57017925 -0.57017925
 -0.57017925 -0.57017925 -0.57017925 -0.57017925         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan]
  warnings.warn(

Matching confounds to amplitudes_21 fold 4
Matching g-factor to amplitudes_21 fold 4
Applying ConfoundRegressor to amplitudes_21 fold 4
Fitting PLS to amplitudes_21 fold 4
Fitting 10 folds for each of 35 candidates, totalling 350 fits
[CV 3/10] END ..................n_components=1;, score=-0.573 total time=   0.0s
[CV 4/10] END ..................n_components=1;, score=-0.561 total time=   0.0s
[CV 2/10] END ..................n_components=1;, score=-0.586 total time=   0.0s
[CV 7/10] END ..................n_components=1;, score=-0.567 total time=   0.0s
[CV 8/10] END ..................n_components=1;, score=-0.570 total time=   0.0s
[CV 5/10] END ..................n_components=1;, score=-0.566 total time=   0.0s
[CV 1/10] END ..................n_components=1;, score=-0.560 total time=   0.0s
[CV 6/10] END ..................n_components=1;, score=-0.553 total time=   0.0s
[CV 9/10] END ..................n_components=1;, score=-0.569 total time=   0.0s
[CV 10/10] END .................n_components=1;, score=-0.562 total time=   0.0s
[CV 4/10] END ..................n_components=2;, score=-0.560 total time=   0.0s
[CV 2/10] END ..................n_components=2;, score=-0.587 total time=   0.0s
[CV 7/10] END ..................n_components=2;, score=-0.562 total time=   0.0s
[CV 8/10] END ..................n_components=2;, score=-0.568 total time=   0.0s
[CV 5/10] END ..................n_components=2;, score=-0.563 total time=   0.0s
[CV 10/10] END .................n_components=2;, score=-0.558 total time=   0.0s
[CV 1/10] END ..................n_components=2;, score=-0.560 total time=   0.0s
[CV 9/10] END ..................n_components=2;, score=-0.568 total time=   0.0s
[CV 6/10] END ..................n_components=2;, score=-0.551 total time=   0.0s
[CV 3/10] END ..................n_components=2;, score=-0.570 total time=   0.0s
[CV 2/10] END ..................n_components=3;, score=-0.587 total time=   0.0s
[CV 1/10] END ..................n_components=3;, score=-0.560 total time=   0.0s
[CV 3/10] END ..................n_components=3;, score=-0.570 total time=   0.0s
[CV 7/10] END ..................n_components=3;, score=-0.562 total time=   0.0s[CV 6/10] END ..................n_components=3;, score=-0.551 total time=   0.0s

[CV 4/10] END ..................n_components=3;, score=-0.559 total time=   0.0s[CV 9/10] END ..................n_components=3;, score=-0.568 total time=   0.0s

[CV 5/10] END ..................n_components=3;, score=-0.563 total time=   0.0s
[CV 8/10] END ..................n_components=3;, score=-0.568 total time=   0.0s
[CV 1/10] END ..................n_components=4;, score=-0.560 total time=   0.0s
[CV 3/10] END ..................n_components=4;, score=-0.570 total time=   0.0s
[CV 10/10] END .................n_components=3;, score=-0.557 total time=   0.0s
[CV 7/10] END ..................n_components=4;, score=-0.563 total time=   0.0s
[CV 9/10] END ..................n_components=4;, score=-0.568 total time=   0.0s
[CV 2/10] END ..................n_components=4;, score=-0.587 total time=   0.0s
[CV 5/10] END ..................n_components=4;, score=-0.563 total time=   0.0s
[CV 1/10] END ..................n_components=5;, score=-0.560 total time=   0.0s[CV 10/10] END .................n_components=4;, score=-0.557 total time=   0.0s

[CV 4/10] END ..................n_components=4;, score=-0.559 total time=   0.0s
[CV 3/10] END ..................n_components=5;, score=-0.570 total time=   0.0s
[CV 9/10] END ..................n_components=5;, score=-0.568 total time=   0.0s
[CV 7/10] END ..................n_components=5;, score=-0.563 total time=   0.0s
[CV 1/10] END ..................n_components=6;, score=-0.560 total time=   0.0s
[CV 5/10] END ..................n_components=5;, score=-0.563 total time=   0.0s
[CV 6/10] END ..................n_components=4;, score=-0.550 total time=   0.0s
[CV 5/10] END ..................n_components=6;, score=-0.563 total time=   0.0s
[CV 8/10] END ..................n_components=4;, score=-0.568 total time=   0.0s
[CV 4/10] END ..................n_components=5;, score=-0.559 total time=   0.0s
[CV 2/10] END ..................n_components=5;, score=-0.587 total time=   0.0s
[CV 2/10] END ..................n_components=6;, score=-0.587 total time=   0.0s
[CV 3/10] END ..................n_components=6;, score=-0.570 total time=   0.0s
[CV 8/10] END ..................n_components=5;, score=-0.568 total time=   0.0s
[CV 6/10] END ..................n_components=6;, score=-0.550 total time=   0.0s
[CV 10/10] END .................n_components=5;, score=-0.557 total time=   0.0s
[CV 9/10] END ..................n_components=6;, score=-0.568 total time=   0.0s
[CV 3/10] END ..................n_components=7;, score=-0.570 total time=   0.0s
[CV 6/10] END ..................n_components=5;, score=-0.550 total time=   0.0s
[CV 3/10] END ..................n_components=8;, score=-0.570 total time=   0.0s[CV 7/10] END ..................n_components=6;, score=-0.563 total time=   0.0s

[CV 4/10] END ..................n_components=6;, score=-0.559 total time=   0.0s
[CV 7/10] END ..................n_components=7;, score=-0.563 total time=   0.0s
[CV 5/10] END ..................n_components=8;, score=-0.563 total time=   0.0s
[CV 10/10] END .................n_components=6;, score=-0.557 total time=   0.0s
[CV 5/10] END ..................n_components=7;, score=-0.563 total time=   0.1s
[CV 4/10] END ..................n_components=8;, score=-0.559 total time=   0.0s
[CV 4/10] END ..................n_components=7;, score=-0.559 total time=   0.0s
[CV 9/10] END ..................n_components=7;, score=-0.568 total time=   0.0s
[CV 1/10] END ..................n_components=9;, score=-0.560 total time=   0.0s
[CV 1/10] END ..................n_components=7;, score=-0.560 total time=   0.1s
[CV 1/10] END ..................n_components=8;, score=-0.560 total time=   0.1s
[CV 7/10] END ..................n_components=8;, score=-0.563 total time=   0.1s[CV 9/10] END ..................n_components=8;, score=-0.568 total time=   0.1s

[CV 8/10] END ..................n_components=6;, score=-0.568 total time=   0.0s
[CV 6/10] END ..................n_components=8;, score=-0.550 total time=   0.0s
[CV 8/10] END ..................n_components=7;, score=-0.568 total time=   0.0s
[CV 10/10] END .................n_components=7;, score=-0.557 total time=   0.0s
[CV 7/10] END ..................n_components=9;, score=-0.563 total time=   0.0s
[CV 2/10] END ..................n_components=9;, score=-0.587 total time=   0.0s
[CV 5/10] END ..................n_components=9;, score=-0.563 total time=   0.1s
[CV 6/10] END ..................n_components=7;, score=-0.550 total time=   0.1s
[CV 3/10] END ..................n_components=9;, score=-0.570 total time=   0.1s
[CV 2/10] END ..................n_components=7;, score=-0.587 total time=   0.1s
[CV 1/10] END .................n_components=10;, score=-0.560 total time=   0.1s
[CV 8/10] END ..................n_components=9;, score=-0.568 total time=   0.0s
[CV 9/10] END ..................n_components=9;, score=-0.568 total time=   0.1s
[CV 2/10] END ..................n_components=8;, score=-0.587 total time=   0.1s
[CV 9/10] END .................n_components=10;, score=-0.568 total time=   0.0s
[CV 8/10] END ..................n_components=8;, score=-0.568 total time=   0.1s
[CV 10/10] END .................n_components=8;, score=-0.557 total time=   0.1s
[CV 1/10] END .................n_components=12;, score=-0.560 total time=   0.0s
[CV 7/10] END .................n_components=11;, score=-0.563 total time=   0.1s
[CV 5/10] END .................n_components=10;, score=-0.563 total time=   0.1s
[CV 4/10] END ..................n_components=9;, score=-0.559 total time=   0.1s
[CV 6/10] END ..................n_components=9;, score=-0.550 total time=   0.1s[CV 2/10] END .................n_components=12;, score=-0.587 total time=   0.0s

[CV 3/10] END .................n_components=11;, score=-0.570 total time=   0.1s
[CV 10/10] END ................n_components=10;, score=-0.557 total time=   0.0s
[CV 2/10] END .................n_components=10;, score=-0.587 total time=   0.1s
[CV 3/10] END .................n_components=12;, score=-0.570 total time=   0.0s[CV 5/10] END .................n_components=12;, score=-0.563 total time=   0.1s

[CV 10/10] END .................n_components=9;, score=-0.557 total time=   0.1s
[CV 8/10] END .................n_components=11;, score=-0.568 total time=   0.1s
[CV 9/10] END .................n_components=12;, score=-0.568 total time=   0.1s
[CV 6/10] END .................n_components=10;, score=-0.550 total time=   0.1s
[CV 3/10] END .................n_components=13;, score=-0.570 total time=   0.1s
[CV 4/10] END .................n_components=12;, score=-0.559 total time=   0.0s
[CV 1/10] END .................n_components=11;, score=-0.560 total time=   0.1s
[CV 1/10] END .................n_components=14;, score=-0.560 total time=   0.1s
[CV 9/10] END .................n_components=11;, score=-0.568 total time=   0.1s
[CV 3/10] END .................n_components=10;, score=-0.570 total time=   0.1s
[CV 5/10] END .................n_components=14;, score=-0.563 total time=   0.1s
[CV 6/10] END .................n_components=12;, score=-0.550 total time=   0.1s
[CV 7/10] END .................n_components=13;, score=-0.563 total time=   0.1s
[CV 7/10] END .................n_components=10;, score=-0.563 total time=   0.1s
[CV 1/10] END .................n_components=16;, score=-0.560 total time=   0.0s
[CV 3/10] END .................n_components=15;, score=-0.570 total time=   0.1s
[CV 4/10] END .................n_components=13;, score=-0.559 total time=   0.1s
[CV 2/10] END .................n_components=11;, score=-0.587 total time=   0.1s
[CV 9/10] END .................n_components=14;, score=-0.568 total time=   0.1s
[CV 10/10] END ................n_components=11;, score=-0.557 total time=   0.1s
[CV 10/10] END ................n_components=12;, score=-0.557 total time=   0.1s
[CV 4/10] END .................n_components=10;, score=-0.559 total time=   0.1s
[CV 7/10] END .................n_components=15;, score=-0.563 total time=   0.1s
[CV 2/10] END .................n_components=16;, score=-0.587 total time=   0.0s
[CV 2/10] END .................n_components=14;, score=-0.587 total time=   0.1s
[CV 4/10] END .................n_components=11;, score=-0.559 total time=   0.2s
[CV 7/10] END .................n_components=12;, score=-0.563 total time=   0.1s
[CV 1/10] END .................n_components=13;, score=-0.560 total time=   0.0s
[CV 5/10] END .................n_components=13;, score=-0.563 total time=   0.1s
[CV 8/10] END .................n_components=10;, score=-0.568 total time=   0.1s
[CV 8/10] END .................n_components=13;, score=-0.568 total time=   0.1s
[CV 3/10] END .................n_components=16;, score=-0.570 total time=   0.0s
[CV 5/10] END .................n_components=16;, score=-0.563 total time=   0.1s
[CV 2/10] END .................n_components=13;, score=-0.587 total time=   0.0s
[CV 4/10] END .................n_components=15;, score=-0.559 total time=   0.1s
[CV 9/10] END .................n_components=16;, score=-0.568 total time=   0.1s
[CV 10/10] END ................n_components=14;, score=-0.557 total time=   0.1s[CV 3/10] END .................n_components=14;, score=-0.570 total time=   0.1s

[CV 6/10] END .................n_components=13;, score=-0.550 total time=   0.1s
[CV 4/10] END .................n_components=16;, score=-0.559 total time=   0.0s
[CV 8/10] END .................n_components=12;, score=-0.568 total time=   0.1s
[CV 3/10] END .................n_components=17;, score=-0.570 total time=   0.1s
[CV 9/10] END .................n_components=13;, score=-0.568 total time=   0.1s
[CV 1/10] END .................n_components=18;, score=-0.560 total time=   0.0s
[CV 6/10] END .................n_components=14;, score=-0.550 total time=   0.2s
[CV 5/10] END .................n_components=11;, score=-0.563 total time=   0.1s
[CV 8/10] END .................n_components=15;, score=-0.568 total time=   0.1s
[CV 6/10] END .................n_components=16;, score=-0.550 total time=   0.1s
[CV 2/10] END .................n_components=18;, score=-0.587 total time=   0.0s
[CV 5/10] END .................n_components=15;, score=-0.563 total time=   0.1s
[CV 9/10] END .................n_components=18;, score=-0.568 total time=   0.1s
[CV 10/10] END ................n_components=16;, score=-0.557 total time=   0.1s
[CV 4/10] END .................n_components=17;, score=-0.559 total time=   0.1s
[CV 7/10] END .................n_components=17;, score=-0.563 total time=   0.1s
[CV 5/10] END .................n_components=18;, score=-0.563 total time=   0.1s
[CV 1/10] END .................n_components=15;, score=-0.560 total time=   0.1s
[CV 4/10] END .................n_components=14;, score=-0.559 total time=   0.1s
[CV 3/10] END .................n_components=18;, score=-0.570 total time=   0.0s
[CV 10/10] END ................n_components=13;, score=-0.557 total time=   0.1s
[CV 7/10] END .................n_components=14;, score=-0.563 total time=   0.1s
[CV 10/10] END ................n_components=18;, score=-0.557 total time=   0.1s
[CV 7/10] END .................n_components=16;, score=-0.563 total time=   0.1s
[CV 6/10] END .................n_components=11;, score=-0.550 total time=   0.1s
[CV 4/10] END .................n_components=18;, score=-0.559 total time=   0.0s
[CV 9/10] END .................n_components=15;, score=-0.568 total time=   0.1s
[CV 6/10] END .................n_components=15;, score=-0.550 total time=   0.1s
[CV 3/10] END .................n_components=19;, score=-0.570 total time=   0.1s
[CV 1/10] END .................n_components=19;, score=-0.560 total time=   0.0s
[CV 5/10] END .................n_components=17;, score=-0.563 total time=   0.1s
[CV 1/10] END .................n_components=17;, score=-0.560 total time=   0.1s
[CV 8/10] END .................n_components=14;, score=-0.568 total time=   0.1s
[CV 7/10] END .................n_components=19;, score=-0.563 total time=   0.1s
[CV 2/10] END .................n_components=15;, score=-0.587 total time=   0.1s
[CV 9/10] END .................n_components=20;, score=-0.568 total time=   0.1s
[CV 6/10] END .................n_components=18;, score=-0.550 total time=   0.1s
[CV 10/10] END ................n_components=15;, score=-0.557 total time=   0.1s
[CV 8/10] END .................n_components=17;, score=-0.568 total time=   0.1s
[CV 8/10] END .................n_components=16;, score=-0.568 total time=   0.1s
[CV 1/10] END .................n_components=20;, score=-0.560 total time=   0.1s
[CV 4/10] END .................n_components=19;, score=-0.559 total time=   0.1s
[CV 3/10] END .................n_components=21;, score=-0.570 total time=   0.1s
[CV 8/10] END .................n_components=19;, score=-0.568 total time=   0.1s
[CV 10/10] END ................n_components=20;, score=-0.557 total time=   0.1s
[CV 2/10] END .................n_components=19;, score=-0.587 total time=   0.1s
[CV 3/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 7/10] END .................n_components=21;, score=-0.563 total time=   0.1s
[CV 5/10] END .................n_components=20;, score=-0.563 total time=   0.2s
[CV 4/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 7/10] END .................n_components=18;, score=-0.563 total time=   0.1s
[CV 1/10] END .................n_components=22;, score=-0.560 total time=   0.1s
[CV 5/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 2/10] END .................n_components=17;, score=-0.587 total time=   0.1s
[CV 6/10] END .................n_components=17;, score=-0.550 total time=   0.1s
[CV 5/10] END .................n_components=22;, score=-0.563 total time=   0.1s
[CV 6/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 1/10] END .................n_components=21;, score=-0.560 total time=   0.1s
[CV 7/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 9/10] END .................n_components=17;, score=-0.568 total time=   0.1s
[CV 8/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 9/10] END ....................n_components=23;, score=nan total time=   0.0s
[CV 5/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 10/10] END ...................n_components=23;, score=nan total time=   0.0s
[CV 1/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 6/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 4/10] END .................n_components=21;, score=-0.559 total time=   0.1s
[CV 9/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 2/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 10/10] END ...................n_components=24;, score=nan total time=   0.0s
[CV 7/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 2/10] END .................n_components=20;, score=-0.587 total time=   0.1s
[CV 9/10] END .................n_components=22;, score=-0.568 total time=   0.1s
[CV 1/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 2/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 9/10] END .................n_components=19;, score=-0.568 total time=   0.1s
[CV 8/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 3/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 6/10] END .................n_components=20;, score=-0.550 total time=   0.1s
[CV 2/10] END .................n_components=21;, score=-0.587 total time=   0.1s
[CV 3/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 5/10] END .................n_components=19;, score=-0.563 total time=   0.1s
[CV 4/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 8/10] END .................n_components=18;, score=-0.568 total time=   0.1s
[CV 4/10] END ....................n_components=24;, score=nan total time=   0.0s
[CV 5/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 6/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 7/10] END ....................n_components=25;, score=nan total time=   0.0s[CV 1/10] END ....................n_components=26;, score=nan total time=   0.0s

[CV 2/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 3/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 4/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 5/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 3/10] END ....................n_components=27;, score=nan total time=   0.0s
[CV 9/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 8/10] END ....................n_components=25;, score=nan total time=   0.0s
[CV 4/10] END ....................n_components=27;, score=nan total time=   0.0s
[CV 7/10] END ....................n_components=27;, score=nan total time=   0.0s
[CV 5/10] END ....................n_components=27;, score=nan total time=   0.0s
[CV 8/10] END ....................n_components=27;, score=nan total time=   0.0s
[CV 6/10] END ....................n_components=26;, score=nan total time=   0.0s
[CV 6/10] END ....................n_components=27;, score=nan total time=   0.0s
[CV 9/10] END ....................n_components=27;, score=nan total time=   0.0s
[CV 10/10] END ...................n_components=26;, score=nan total time=   0.0s
[CV 8/10] END .................n_components=21;, score=-0.568 total time=   0.1s
[CV 10/10] END ...................n_components=27;, score=nan total time=   0.0s

/home/irinabu/anaconda3/envs/ukbiobank_py11/lib/python3.11/site-packages/sklearn/model_selection/_search.py:976: UserWarning: One or more of the test scores are non-finite: [-0.56682007 -0.56470923 -0.56447042 -0.5644486  -0.56442903 -0.56446243
 -0.56445279 -0.56444994 -0.56444969 -0.56444978 -0.56444983 -0.56444983
 -0.56444983 -0.56444983 -0.56444983 -0.56444983 -0.56444983 -0.56444983
 -0.56444983 -0.56444983 -0.56444983 -0.56444983         nan         nan
         nan         nan         nan         nan         nan         nan
         nan         nan         nan         nan         nan]
  warnings.warn(

Fold = 4
----------
MSE =  0.5153165510159669
MAE =  0.5643535999245028
R2 =  0.018271613342813242
Pearson's r =  PearsonRResult(statistic=0.1377301113689935, pvalue=4.4180304939263486e-24)
----------
Started amplitudes_55
Matching brain data to confounds in amplitudes_55
Matching brain data to confounds in amplitudes_55
Matching confounds to amplitudes_55 fold 0
Matching g-factor to amplitudes_55 fold 0
Applying ConfoundRegressor to amplitudes_55 fold 0
Fitting PLS to amplitudes_55 fold 0
Fitting 10 folds for each of 35 candidates, totalling 350 fits
[CV 6/10] END ..................n_components=1;, score=-0.560 total time=   0.1s
[CV 1/10] END ..................n_components=1;, score=-0.565 total time=   0.1s
[CV 3/10] END ..................n_components=1;, score=-0.577 total time=   0.1s
[CV 2/10] END ..................n_components=1;, score=-0.556 total time=   0.1s
[CV 8/10] END ..................n_components=1;, score=-0.569 total time=   0.1s
[CV 2/10] END ..................n_components=2;, score=-0.554 total time=   0.1s
[CV 7/10] END ..................n_components=1;, score=-0.557 total time=   0.1s
[CV 4/10] END ..................n_components=1;, score=-0.560 total time=   0.1s
[CV 10/10] END .................n_components=1;, score=-0.573 total time=   0.1s
[CV 9/10] END ..................n_components=1;, score=-0.540 total time=   0.1s
[CV 5/10] END ..................n_components=1;, score=-0.570 total time=   0.1s
[CV 1/10] END ..................n_components=2;, score=-0.562 total time=   0.1s
[CV 3/10] END ..................n_components=2;, score=-0.573 total time=   0.1s
[CV 5/10] END ..................n_components=2;, score=-0.566 total time=   0.1s
[CV 4/10] END ..................n_components=2;, score=-0.557 total time=   0.1s
[CV 5/10] END ..................n_components=3;, score=-0.566 total time=   0.0s
[CV 9/10] END ..................n_components=3;, score=-0.534 total time=   0.0s
[CV 7/10] END ..................n_components=2;, score=-0.555 total time=   0.1s
[CV 6/10] END ..................n_components=3;, score=-0.555 total time=   0.1s
[CV 7/10] END ..................n_components=3;, score=-0.556 total time=   0.1s
[CV 2/10] END ..................n_components=3;, score=-0.553 total time=   0.1s
[CV 8/10] END ..................n_components=2;, score=-0.564 total time=   0.1s
[CV 4/10] END ..................n_components=3;, score=-0.557 total time=   0.1s
[CV 6/10] END ..................n_components=2;, score=-0.557 total time=   0.1s[CV 10/10] END .................n_components=2;, score=-0.571 total time=   0.1s

[CV 3/10] END ..................n_components=3;, score=-0.571 total time=   0.1s
[CV 9/10] END ..................n_components=2;, score=-0.535 total time=   0.1s
[CV 8/10] END ..................n_components=3;, score=-0.563 total time=   0.1s
[CV 7/10] END ..................n_components=4;, score=-0.556 total time=   0.1s
[CV 1/10] END ..................n_components=3;, score=-0.560 total time=   0.1s
[CV 3/10] END ..................n_components=4;, score=-0.571 total time=   0.1s
[CV 5/10] END ..................n_components=5;, score=-0.565 total time=   0.1s
[CV 10/10] END .................n_components=3;, score=-0.567 total time=   0.1s
[CV 1/10] END ..................n_components=4;, score=-0.559 total time=   0.1s
[CV 8/10] END ..................n_components=4;, score=-0.563 total time=   0.1s
[CV 9/10] END ..................n_components=4;, score=-0.533 total time=   0.1s
[CV 5/10] END ..................n_components=4;, score=-0.566 total time=   0.1s
[CV 6/10] END ..................n_components=5;, score=-0.556 total time=   0.1s
[CV 9/10] END ..................n_components=5;, score=-0.533 total time=   0.1s
[CV 1/10] END ..................n_components=5;, score=-0.558 total time=   0.2s
[CV 7/10] END ..................n_components=5;, score=-0.556 total time=   0.2s
[CV 3/10] END ..................n_components=5;, score=-0.571 total time=   0.2s
[CV 1/10] END ..................n_components=6;, score=-0.558 total time=   0.2s
[CV 4/10] END ..................n_components=4;, score=-0.557 total time=   0.1s
[CV 7/10] END ..................n_components=6;, score=-0.556 total time=   0.2s
[CV 10/10] END .................n_components=4;, score=-0.567 total time=   0.1s
[CV 2/10] END ..................n_components=4;, score=-0.553 total time=   0.1s
[CV 5/10] END ..................n_components=6;, score=-0.565 total time=   0.2s
[CV 3/10] END ..................n_components=6;, score=-0.571 total time=   0.2s
[CV 6/10] END ..................n_components=4;, score=-0.556 total time=   0.1s
[CV 3/10] END ..................n_components=7;, score=-0.571 total time=   0.1s
[CV 10/10] END .................n_components=5;, score=-0.567 total time=   0.2s
[CV 4/10] END ..................n_components=7;, score=-0.558 total time=   0.1s
[CV 9/10] END ..................n_components=6;, score=-0.533 total time=   0.2s
[CV 8/10] END ..................n_components=5;, score=-0.563 total time=   0.2s
[CV 2/10] END ..................n_components=5;, score=-0.553 total time=   0.2s
[CV 4/10] END ..................n_components=5;, score=-0.558 total time=   0.2s
[CV 5/10] END ..................n_components=7;, score=-0.565 total time=   0.2s
[CV 1/10] END ..................n_components=7;, score=-0.558 total time=   0.3s
[CV 2/10] END ..................n_components=6;, score=-0.553 total time=   0.2s
[CV 8/10] END ..................n_components=6;, score=-0.563 total time=   0.2s
[CV 7/10] END ..................n_components=7;, score=-0.556 total time=   0.2s
[CV 5/10] END ..................n_components=8;, score=-0.565 total time=   0.1s
[CV 6/10] END ..................n_components=6;, score=-0.556 total time=   0.2s
[CV 4/10] END ..................n_components=6;, score=-0.558 total time=   0.2s
[CV 9/10] END ..................n_components=7;, score=-0.533 total time=   0.2s
[CV 1/10] END ..................n_components=8;, score=-0.558 total time=   0.2s
[CV 6/10] END ..................n_components=8;, score=-0.556 total time=   0.1s
[CV 9/10] END ..................n_components=8;, score=-0.533 total time=   0.2s
[CV 6/10] END ..................n_components=7;, score=-0.556 total time=   0.2s
[CV 3/10] END ..................n_components=8;, score=-0.571 total time=   0.2s
[CV 1/10] END ..................n_components=9;, score=-0.558 total time=   0.2s
[CV 2/10] END ..................n_components=7;, score=-0.554 total time=   0.2s
[CV 8/10] END ..................n_components=7;, score=-0.563 total time=   0.2s
[CV 10/10] END .................n_components=6;, score=-0.567 total time=   0.3s
[CV 7/10] END ..................n_components=8;, score=-0.556 total time=   0.3s
[CV 1/10] END .................n_components=10;, score=-0.558 total time=   0.1s
[CV 10/10] END .................n_components=7;, score=-0.567 total time=   0.2s
[CV 7/10] END ..................n_components=9;, score=-0.556 total time=   0.2s
[CV 5/10] END ..................n_components=9;, score=-0.565 total time=   0.2s
[CV 3/10] END ..................n_components=9;, score=-0.571 total time=   0.3s
[CV 2/10] END ..................n_components=8;, score=-0.554 total time=   0.3s
[CV 2/10] END .................n_components=10;, score=-0.553 total time=   0.1s
[CV 9/10] END ..................n_components=9;, score=-0.533 total time=   0.3s
[CV 9/10] END .................n_components=10;, score=-0.533 total time=   0.2s
[CV 10/10] END .................n_components=8;, score=-0.567 total time=   0.2s
[CV 2/10] END ..................n_components=9;, score=-0.553 total time=   0.2s
[CV 7/10] END .................n_components=10;, score=-0.556 total time=   0.2s
[CV 4/10] END ..................n_components=8;, score=-0.558 total time=   0.3s
[CV 8/10] END ..................n_components=8;, score=-0.563 total time=   0.2s
[CV 3/10] END .................n_components=10;, score=-0.571 total time=   0.3s
[CV 5/10] END .................n_components=11;, score=-0.565 total time=   0.1s
[CV 10/10] END ................n_components=10;, score=-0.567 total time=   0.1s
[CV 8/10] END ..................n_components=9;, score=-0.563 total time=   0.2s
[CV 5/10] END .................n_components=10;, score=-0.565 total time=   0.3s
[CV 6/10] END ..................n_components=9;, score=-0.556 total time=   0.2s
[CV 1/10] END .................n_components=11;, score=-0.558 total time=   0.3s
[CV 4/10] END ..................n_components=9;, score=-0.558 total time=   0.3s
[CV 6/10] END .................n_components=11;, score=-0.556 total time=   0.1s
[CV 10/10] END .................n_components=9;, score=-0.567 total time=   0.2s
[CV 5/10] END .................n_components=12;, score=-0.565 total time=   0.1s
[CV 7/10] END .................n_components=11;, score=-0.556 total time=   0.3s
[CV 8/10] END .................n_components=10;, score=-0.563 total time=   0.2s
[CV 9/10] END .................n_components=11;, score=-0.533 total time=   0.3s
[CV 3/10] END .................n_components=11;, score=-0.571 total time=   0.3s
[CV 4/10] END .................n_components=10;, score=-0.558 total time=   0.2s
[CV 1/10] END .................n_components=12;, score=-0.558 total time=   0.3s
[CV 3/10] END .................n_components=13;, score=-0.571 total time=   0.1s
[CV 6/10] END .................n_components=12;, score=-0.556 total time=   0.1s
[CV 7/10] END .................n_components=12;, score=-0.556 total time=   0.3s
[CV 6/10] END .................n_components=10;, score=-0.556 total time=   0.3s
[CV 3/10] END .................n_components=12;, score=-0.571 total time=   0.4s
[CV 2/10] END .................n_components=11;, score=-0.553 total time=   0.3s
[CV 9/10] END .................n_components=12;, score=-0.533 total time=   0.3s
[CV 5/10] END .................n_components=13;, score=-0.565 total time=   0.2s
[CV 4/10] END .................n_components=13;, score=-0.558 total time=   0.1s
[CV 8/10] END .................n_components=12;, score=-0.563 total time=   0.1s
[CV 1/10] END .................n_components=14;, score=-0.558 total time=   0.2s
[CV 8/10] END .................n_components=11;, score=-0.563 total time=   0.3s
[CV 10/10] END ................n_components=11;, score=-0.567 total time=   0.3s
[CV 9/10] END .................n_components=13;, score=-0.533 total time=   0.3s
[CV 1/10] END .................n_components=13;, score=-0.558 total time=   0.4s
[CV 4/10] END .................n_components=11;, score=-0.558 total time=   0.3s
[CV 7/10] END .................n_components=14;, score=-0.556 total time=   0.1s
[CV 9/10] END .................n_components=14;, score=-0.533 total time=   0.1s
[CV 2/10] END .................n_components=14;, score=-0.553 total time=   0.2s
[CV 7/10] END .................n_components=13;, score=-0.556 total time=   0.4s
[CV 2/10] END .................n_components=12;, score=-0.553 total time=   0.4s
[CV 6/10] END .................n_components=13;, score=-0.556 total time=   0.3s
[CV 10/10] END ................n_components=12;, score=-0.567 total time=   0.3s
[CV 3/10] END .................n_components=14;, score=-0.571 total time=   0.4s
[CV 4/10] END .................n_components=12;, score=-0.558 total time=   0.4s
[CV 5/10] END .................n_components=14;, score=-0.565 total time=   0.4s
[CV 10/10] END ................n_components=14;, score=-0.567 total time=   0.2s
[CV 8/10] END .................n_components=14;, score=-0.563 total time=   0.2s
[CV 10/10] END ................n_components=13;, score=-0.567 total time=   0.2s
[CV 7/10] END .................n_components=15;, score=-0.556 total time=   0.2s
[CV 1/10] END .................n_components=15;, score=-0.558 total time=   0.4s
[CV 7/10] END .................n_components=16;, score=-0.556 total time=   0.2s
[CV 3/10] END .................n_components=15;, score=-0.571 total time=   0.4s
[CV 8/10] END .................n_components=15;, score=-0.563 total time=   0.2s
[CV 8/10] END .................n_components=13;, score=-0.563 total time=   0.3s
[CV 2/10] END .................n_components=13;, score=-0.553 total time=   0.4s
[CV 1/10] END .................n_components=16;, score=-0.558 total time=   0.3s
[CV 5/10] END .................n_components=15;, score=-0.565 total time=   0.4s
[CV 4/10] END .................n_components=14;, score=-0.558 total time=   0.4s
[CV 6/10] END .................n_components=14;, score=-0.556 total time=   0.3s
[CV 9/10] END .................n_components=16;, score=-0.533 total time=   0.3s
[CV 9/10] END .................n_components=15;, score=-0.533 total time=   0.4s
[CV 8/10] END .................n_components=16;, score=-0.563 total time=   0.2s
[CV 3/10] END .................n_components=16;, score=-0.571 total time=   0.4s
[CV 1/10] END .................n_components=17;, score=-0.558 total time=   0.4s
[CV 3/10] END .................n_components=17;, score=-0.571 total time=   0.2s
[CV 2/10] END .................n_components=15;, score=-0.553 total time=   0.3s
[CV 5/10] END .................n_components=16;, score=-0.565 total time=   0.5s
[CV 2/10] END .................n_components=16;, score=-0.553 total time=   0.3s
[CV 4/10] END .................n_components=15;, score=-0.558 total time=   0.3s
[CV 5/10] END .................n_components=17;, score=-0.565 total time=   0.3s
[CV 3/10] END .................n_components=18;, score=-0.571 total time=   0.2s
[CV 4/10] END .................n_components=17;, score=-0.558 total time=   0.2s
[CV 6/10] END .................n_components=15;, score=-0.556 total time=   0.4s
[CV 9/10] END .................n_components=17;, score=-0.533 total time=   0.4s
[CV 2/10] END .................n_components=17;, score=-0.553 total time=   0.3s
[CV 7/10] END .................n_components=17;, score=-0.556 total time=   0.5s
[CV 4/10] END .................n_components=16;, score=-0.558 total time=   0.4s
[CV 1/10] END .................n_components=18;, score=-0.558 total time=   0.4s
[CV 5/10] END .................n_components=18;, score=-0.565 total time=   0.3s
[CV 10/10] END ................n_components=16;, score=-0.567 total time=   0.5s
[CV 10/10] END ................n_components=15;, score=-0.567 total time=   0.5s
[CV 4/10] END .................n_components=18;, score=-0.558 total time=   0.2s
[CV 1/10] END .................n_components=19;, score=-0.558 total time=   0.2s
[CV 6/10] END .................n_components=16;, score=-0.556 total time=   0.4s
[CV 7/10] END .................n_components=18;, score=-0.556 total time=   0.4s
[CV 10/10] END ................n_components=17;, score=-0.567 total time=   0.4s
[CV 6/10] END .................n_components=17;, score=-0.556 total time=   0.4s
[CV 9/10] END .................n_components=18;, score=-0.533 total time=   0.5s
[CV 3/10] END .................n_components=20;, score=-0.571 total time=   0.2s
[CV 2/10] END .................n_components=19;, score=-0.553 total time=   0.2s[CV 5/10] END .................n_components=19;, score=-0.565 total time=   0.4s

[CV 6/10] END .................n_components=18;, score=-0.556 total time=   0.4s
[CV 3/10] END .................n_components=19;, score=-0.571 total time=   0.5s
[CV 2/10] END .................n_components=18;, score=-0.553 total time=   0.4s
[CV 4/10] END .................n_components=20;, score=-0.558 total time=   0.2s
[CV 7/10] END .................n_components=19;, score=-0.556 total time=   0.5s
[CV 8/10] END .................n_components=17;, score=-0.563 total time=   0.5s
[CV 1/10] END .................n_components=21;, score=-0.558 total time=   0.2s
[CV 6/10] END .................n_components=19;, score=-0.556 total time=   0.2s
[CV 1/10] END .................n_components=20;, score=-0.558 total time=   0.5s
[CV 7/10] END .................n_components=20;, score=-0.556 total time=   0.3s
[CV 9/10] END .................n_components=19;, score=-0.533 total time=   0.6s
[CV 8/10] END .................n_components=18;, score=-0.563 total time=   0.4s
[CV 5/10] END .................n_components=20;, score=-0.565 total time=   0.5s
[CV 9/10] END .................n_components=20;, score=-0.533 total time=   0.5s
[CV 10/10] END ................n_components=18;, score=-0.567 total time=   0.5s
[CV 2/10] END .................n_components=21;, score=-0.553 total time=   0.2s
[CV 1/10] END .................n_components=22;, score=-0.558 total time=   0.2s
[CV 2/10] END .................n_components=20;, score=-0.553 total time=   0.2s
[CV 4/10] END .................n_components=19;, score=-0.558 total time=   0.5s
[CV 3/10] END .................n_components=21;, score=-0.571 total time=   0.5s
[CV 8/10] END .................n_components=19;, score=-0.563 total time=   0.4s
[CV 5/10] END .................n_components=21;, score=-0.565 total time=   0.5s
[CV 2/10] END .................n_components=22;, score=-0.553 total time=   0.2s
[CV 9/10] END .................n_components=22;, score=-0.533 total time=   0.2s
[CV 9/10] END .................n_components=21;, score=-0.533 total time=   0.5s
[CV 7/10] END .................n_components=21;, score=-0.556 total time=   0.6s
[CV 8/10] END .................n_components=20;, score=-0.563 total time=   0.5s
[CV 10/10] END ................n_components=19;, score=-0.567 total time=   0.5s
[CV 6/10] END .................n_components=20;, score=-0.556 total time=   0.5s
[CV 5/10] END .................n_components=23;, score=-0.565 total time=   0.2s
[CV 3/10] END .................n_components=22;, score=-0.571 total time=   0.5s
[CV 10/10] END ................n_components=22;, score=-0.567 total time=   0.2s
[CV 10/10] END ................n_components=20;, score=-0.567 total time=   0.5s
[CV 10/10] END ................n_components=21;, score=-0.567 total time=   0.3s
[CV 5/10] END .................n_components=22;, score=-0.565 total time=   0.6s
[CV 1/10] END .................n_components=23;, score=-0.558 total time=   0.5s
[CV 3/10] END .................n_components=24;, score=-0.571 total time=   0.2s
[CV 4/10] END .................n_components=21;, score=-0.558 total time=   0.5s
[CV 6/10] END .................n_components=21;, score=-0.556 total time=   0.5s
[CV 6/10] END .................n_components=23;, score=-0.556 total time=   0.3s
[CV 7/10] END .................n_components=22;, score=-0.556 total time=   0.7s
[CV 3/10] END .................n_components=23;, score=-0.571 total time=   0.6s
[CV 8/10] END .................n_components=21;, score=-0.563 total time=   0.5s
[CV 1/10] END .................n_components=24;, score=-0.558 total time=   0.5s
[CV 3/10] END .................n_components=25;, score=-0.571 total time=   0.2s
[CV 7/10] END .................n_components=23;, score=-0.556 total time=   0.6s
[CV 5/10] END .................n_components=24;, score=-0.565 total time=   0.5s
[CV 9/10] END .................n_components=23;, score=-0.533 total time=   0.7s
[CV 4/10] END .................n_components=22;, score=-0.558 total time=   0.6s
[CV 4/10] END .................n_components=24;, score=-0.558 total time=   0.4s
[CV 2/10] END .................n_components=23;, score=-0.553 total time=   0.5s
[CV 7/10] END .................n_components=24;, score=-0.556 total time=   0.5s
[CV 9/10] END .................n_components=24;, score=-0.533 total time=   0.5s
[CV 4/10] END .................n_components=25;, score=-0.558 total time=   0.2s
[CV 1/10] END .................n_components=25;, score=-0.558 total time=   0.5s
[CV 6/10] END .................n_components=24;, score=-0.556 total time=   0.2s
[CV 8/10] END .................n_components=22;, score=-0.563 total time=   0.5s
[CV 6/10] END .................n_components=22;, score=-0.556 total time=   0.7s
[CV 8/10] END .................n_components=24;, score=-0.563 total time=   0.2s
[CV 4/10] END .................n_components=23;, score=-0.558 total time=   0.6s
[CV 3/10] END .................n_components=26;, score=-0.571 total time=   0.2s

/home/irinabu/anaconda3/envs/ukbiobank_py11/lib/python3.11/site-packages/sklearn/cross_decomposition/_pls.py:319: RuntimeWarning: invalid value encountered in divide
  y_scores = np.dot(Yk, y_weights) / y_ss

[CV 9/10] END .................n_components=33;, score=-0.565 total time=   0.7s
[CV 5/10] END .................n_components=34;, score=-0.558 total time=   0.9s
[CV 8/10] END .................n_components=30;, score=-0.581 total time=   0.8s
[CV 6/10] END .................n_components=33;, score=-0.560 total time=   0.5s
[CV 10/10] END ................n_components=31;, score=-0.557 total time=   0.8s
[CV 7/10] END .................n_components=34;, score=-0.577 total time=   0.9s
[CV 10/10] END ................n_components=34;, score=-0.557 total time=   0.6s
[CV 9/10] END .................n_components=34;, score=-0.565 total time=   0.8s
[CV 10/10] END ................n_components=33;, score=-0.557 total time=   0.4s
[CV 8/10] END .................n_components=35;, score=-0.581 total time=   0.3s
[CV 2/10] END .................n_components=33;, score=-0.565 total time=   0.5s
[CV 4/10] END .................n_components=35;, score=-0.571 total time=   0.7s
[CV 2/10] END .................n_components=35;, score=-0.565 total time=   0.7s
[CV 3/10] END .................n_components=35;, score=-0.575 total time=   0.7s
[CV 6/10] END .................n_components=31;, score=-0.560 total time=   0.9s
[CV 10/10] END ................n_components=35;, score=-0.557 total time=   0.4s
[CV 1/10] END .................n_components=35;, score=-0.562 total time=   0.9s
[CV 5/10] END .................n_components=35;, score=-0.558 total time=   0.7s
[CV 6/10] END .................n_components=35;, score=-0.560 total time=   0.7s
[CV 9/10] END .................n_components=35;, score=-0.565 total time=   0.6s
[CV 7/10] END .................n_components=35;, score=-0.577 total time=   0.7s
Model parameters for fold 3: [{'n_components': 1}, {'n_components': 2}, {'n_components': 3}, {'n_components': 4}, {'n_components': 5}, {'n_components': 6}, {'n_components': 7}, {'n_components': 8}, {'n_components': 9}, {'n_components': 10}, {'n_components': 11}, {'n_components': 12}, {'n_components': 13}, {'n_components': 14}, {'n_components': 15}, {'n_components': 16}, {'n_components': 17}, {'n_components': 18}, {'n_components': 19}, {'n_components': 20}, {'n_components': 21}, {'n_components': 22}, {'n_components': 23}, {'n_components': 24}, {'n_components': 25}, {'n_components': 26}, {'n_components': 27}, {'n_components': 28}, {'n_components': 29}, {'n_components': 30}, {'n_components': 31}, {'n_components': 32}, {'n_components': 33}, {'n_components': 34}, {'n_components': 35}]
Mean test score for fold 3: [-0.57157312 -0.56805913 -0.56692461 -0.56691436 -0.56692465 -0.56700903
 -0.56701452 -0.56701442 -0.56701406 -0.56701419 -0.5670141  -0.56701431
 -0.56701429 -0.5670143  -0.56701431 -0.5670143  -0.56701431 -0.56701431
 -0.56701431 -0.5670143  -0.5670143  -0.5670143  -0.5670143  -0.5670143
 -0.5670143  -0.5670143  -0.5670143  -0.5670143  -0.5670143  -0.5670143
 -0.5670143  -0.5670143  -0.5670143  -0.5670143  -0.5670143 ]
Rank test score for fold 3: [35 34  2  1  3  4 33 32  5  7  6 31  8  9 30 10 28 29 27 26 25 11 12 13
 20 14 15 21 15 15 21 15 21 15 21]
GridSearchCV(cv=KFold(n_splits=10, random_state=42, shuffle=True),
             estimator=PLSRegression(), n_jobs=15,
             param_grid={'n_components': range(1, 36)},
             scoring='neg_mean_absolute_error', verbose=4)
Saving PLS model for amplitudes_55 fold 3
Best params in fold 3 =  {'n_components': 4}
Best score (neg_mean_absolute_error) in fold 3 =  -0.5669143575558013
Predicting & saving g_test for amplitudes_55 fold 3

/home/irinabu/anaconda3/envs/ukbiobank_py11/lib/python3.11/site-packages/sklearn/cross_decomposition/_pls.py:319: RuntimeWarning: invalid value encountered in divide
  y_scores = np.dot(Yk, y_weights) / y_ss

Predicting & saving g_train for amplitudes_55 fold 3
Fold = 3
----------
MSE =  0.4942374357027007
MAE =  0.5575324704073772
R2 =  0.02935349441119317
Pearson's r =  PearsonRResult(statistic=0.17152486651424337, pvalue=1.426746137663854e-36)
----------
Matching brain data to confounds in amplitudes_55
Matching confounds to amplitudes_55 fold 4
Matching g-factor to amplitudes_55 fold 4
Applying ConfoundRegressor to amplitudes_55 fold 4
Fitting PLS to amplitudes_55 fold 4
Fitting 10 folds for each of 35 candidates, totalling 350 fits
[CV 5/10] END ..................n_components=1;, score=-0.566 total time=   0.0s
[CV 2/10] END ..................n_components=1;, score=-0.586 total time=   0.1s
[CV 3/10] END ..................n_components=1;, score=-0.571 total time=   0.1s
[CV 10/10] END .................n_components=1;, score=-0.558 total time=   0.1s
[CV 9/10] END ..................n_components=1;, score=-0.568 total time=   0.1s[CV 4/10] END ..................n_components=2;, score=-0.560 total time=   0.1s

[CV 4/10] END ..................n_components=1;, score=-0.563 total time=   0.1s
[CV 1/10] END ..................n_components=1;, score=-0.559 total time=   0.1s
[CV 1/10] END ..................n_components=2;, score=-0.554 total time=   0.1s
[CV 6/10] END ..................n_components=1;, score=-0.551 total time=   0.1s
[CV 7/10] END ..................n_components=1;, score=-0.568 total time=   0.1s
[CV 5/10] END ..................n_components=2;, score=-0.559 total time=   0.1s
[CV 8/10] END ..................n_components=1;, score=-0.569 total time=   0.1s
[CV 3/10] END ..................n_components=2;, score=-0.568 total time=   0.1s
[CV 2/10] END ..................n_components=2;, score=-0.585 total time=   0.1s
[CV 6/10] END ..................n_components=2;, score=-0.548 total time=   0.1s
[CV 8/10] END ..................n_components=2;, score=-0.566 total time=   0.1s
[CV 7/10] END ..................n_components=2;, score=-0.565 total time=   0.1s
[CV 9/10] END ..................n_components=2;, score=-0.567 total time=   0.1s
[CV 10/10] END .................n_components=2;, score=-0.552 total time=   0.1s
[CV 1/10] END ..................n_components=4;, score=-0.552 total time=   0.1s
[CV 9/10] END ..................n_components=3;, score=-0.564 total time=   0.1s
[CV 1/10] END ..................n_components=3;, score=-0.552 total time=   0.1s
[CV 8/10] END ..................n_components=3;, score=-0.565 total time=   0.1s
[CV 5/10] END ..................n_components=3;, score=-0.559 total time=   0.1s
[CV 2/10] END ..................n_components=3;, score=-0.586 total time=   0.1s
[CV 4/10] END ..................n_components=3;, score=-0.557 total time=   0.1s
[CV 3/10] END ..................n_components=3;, score=-0.567 total time=   0.1s
[CV 6/10] END ..................n_components=3;, score=-0.548 total time=   0.1s
[CV 7/10] END ..................n_components=3;, score=-0.563 total time=   0.1s
[CV 2/10] END ..................n_components=4;, score=-0.586 total time=   0.0s
[CV 10/10] END .................n_components=3;, score=-0.552 total time=   0.1s
[CV 3/10] END ..................n_components=5;, score=-0.568 total time=   0.1s
[CV 5/10] END ..................n_components=4;, score=-0.558 total time=   0.1s
[CV 3/10] END ..................n_components=4;, score=-0.567 total time=   0.1s
[CV 1/10] END ..................n_components=5;, score=-0.552 total time=   0.1s
[CV 9/10] END ..................n_components=4;, score=-0.564 total time=   0.1s
[CV 7/10] END ..................n_components=4;, score=-0.564 total time=   0.1s
[CV 9/10] END ..................n_components=6;, score=-0.565 total time=   0.1s
[CV 5/10] END ..................n_components=5;, score=-0.558 total time=   0.1s
[CV 4/10] END ..................n_components=5;, score=-0.557 total time=   0.1s
[CV 7/10] END ..................n_components=5;, score=-0.563 total time=   0.2s[CV 10/10] END .................n_components=6;, score=-0.552 total time=   0.1s

[CV 2/10] END ..................n_components=5;, score=-0.586 total time=   0.1s
[CV 6/10] END ..................n_components=4;, score=-0.548 total time=   0.1s
[CV 3/10] END ..................n_components=7;, score=-0.567 total time=   0.1s
[CV 9/10] END ..................n_components=5;, score=-0.565 total time=   0.2s
[CV 10/10] END .................n_components=4;, score=-0.552 total time=   0.1s
[CV 4/10] END ..................n_components=4;, score=-0.558 total time=   0.1s
[CV 1/10] END ..................n_components=6;, score=-0.552 total time=   0.2s
[CV 6/10] END ..................n_components=5;, score=-0.549 total time=   0.1s
[CV 8/10] END ..................n_components=4;, score=-0.565 total time=   0.1s
[CV 7/10] END ..................n_components=6;, score=-0.564 total time=   0.2s
[CV 5/10] END ..................n_components=6;, score=-0.558 total time=   0.2s
[CV 3/10] END ..................n_components=6;, score=-0.567 total time=   0.2s
[CV 5/10] END ..................n_components=7;, score=-0.558 total time=   0.1s
[CV 4/10] END ..................n_components=7;, score=-0.557 total time=   0.1s
[CV 1/10] END ..................n_components=7;, score=-0.552 total time=   0.2s
[CV 6/10] END ..................n_components=7;, score=-0.549 total time=   0.1s
[CV 8/10] END ..................n_components=5;, score=-0.565 total time=   0.2s
[CV 9/10] END ..................n_components=8;, score=-0.565 total time=   0.1s
[CV 5/10] END ..................n_components=8;, score=-0.558 total time=   0.1s
[CV 9/10] END ..................n_components=7;, score=-0.565 total time=   0.2s
[CV 10/10] END .................n_components=5;, score=-0.552 total time=   0.2s
[CV 1/10] END ..................n_components=9;, score=-0.552 total time=   0.1s
[CV 1/10] END ..................n_components=8;, score=-0.552 total time=   0.2s
[CV 8/10] END ..................n_components=6;, score=-0.565 total time=   0.2s
[CV 10/10] END .................n_components=8;, score=-0.552 total time=   0.1s
[CV 7/10] END ..................n_components=8;, score=-0.564 total time=   0.2s
[CV 6/10] END ..................n_components=8;, score=-0.549 total time=   0.1s
[CV 3/10] END ..................n_components=8;, score=-0.567 total time=   0.2s
[CV 6/10] END ..................n_components=6;, score=-0.549 total time=   0.2s
[CV 2/10] END ..................n_components=6;, score=-0.586 total time=   0.2s
[CV 4/10] END ..................n_components=6;, score=-0.557 total time=   0.2s
[CV 7/10] END ..................n_components=7;, score=-0.564 total time=   0.3s
[CV 2/10] END ..................n_components=9;, score=-0.586 total time=   0.1s
[CV 7/10] END ..................n_components=9;, score=-0.564 total time=   0.1s
[CV 10/10] END .................n_components=7;, score=-0.552 total time=   0.2s
[CV 2/10] END ..................n_components=7;, score=-0.586 total time=   0.2s
[CV 1/10] END .................n_components=10;, score=-0.552 total time=   0.1s
[CV 3/10] END .................n_components=11;, score=-0.567 total time=   0.1s
[CV 7/10] END .................n_components=11;, score=-0.564 total time=   0.1s
[CV 8/10] END ..................n_components=9;, score=-0.565 total time=   0.1s
[CV 2/10] END ..................n_components=8;, score=-0.586 total time=   0.2s
[CV 3/10] END ..................n_components=9;, score=-0.567 total time=   0.3s
[CV 8/10] END ..................n_components=8;, score=-0.565 total time=   0.2s
[CV 5/10] END ..................n_components=9;, score=-0.558 total time=   0.3s
[CV 4/10] END ..................n_components=8;, score=-0.557 total time=   0.2s
[CV 4/10] END .................n_components=11;, score=-0.557 total time=   0.1s
[CV 9/10] END ..................n_components=9;, score=-0.565 total time=   0.3s
[CV 8/10] END .................n_components=11;, score=-0.565 total time=   0.1s
[CV 9/10] END .................n_components=12;, score=-0.565 total time=   0.1s
[CV 5/10] END .................n_components=10;, score=-0.558 total time=   0.3s
[CV 2/10] END .................n_components=10;, score=-0.586 total time=   0.2s
[CV 8/10] END ..................n_components=7;, score=-0.565 total time=   0.3s
[CV 9/10] END .................n_components=10;, score=-0.565 total time=   0.3s
[CV 5/10] END .................n_components=11;, score=-0.558 total time=   0.1s
[CV 9/10] END .................n_components=11;, score=-0.565 total time=   0.1s
[CV 1/10] END .................n_components=12;, score=-0.552 total time=   0.3s
[CV 10/10] END ................n_components=12;, score=-0.552 total time=   0.1s
[CV 4/10] END ..................n_components=9;, score=-0.557 total time=   0.3s
[CV 5/10] END .................n_components=12;, score=-0.558 total time=   0.3s
[CV 10/10] END ................n_components=11;, score=-0.552 total time=   0.1s
[CV 6/10] END .................n_components=11;, score=-0.549 total time=   0.1s
[CV 6/10] END ..................n_components=9;, score=-0.549 total time=   0.3s
[CV 10/10] END .................n_components=9;, score=-0.552 total time=   0.2s
[CV 6/10] END .................n_components=10;, score=-0.549 total time=   0.2s
[CV 3/10] END .................n_components=13;, score=-0.567 total time=   0.3s
[CV 1/10] END .................n_components=14;, score=-0.552 total time=   0.3s
[CV 1/10] END .................n_components=13;, score=-0.552 total time=   0.1s
[CV 3/10] END .................n_components=10;, score=-0.567 total time=   0.2s
[CV 7/10] END .................n_components=13;, score=-0.564 total time=   0.4s
[CV 10/10] END ................n_components=10;, score=-0.552 total time=   0.3s
[CV 2/10] END .................n_components=13;, score=-0.586 total time=   0.1s
[CV 2/10] END .................n_components=12;, score=-0.586 total time=   0.3s
[CV 7/10] END .................n_components=10;, score=-0.564 total time=   0.2s
[CV 7/10] END .................n_components=15;, score=-0.564 total time=   0.2s
[CV 4/10] END .................n_components=10;, score=-0.557 total time=   0.2s
[CV 5/10] END .................n_components=14;, score=-0.558 total time=   0.4s
[CV 3/10] END .................n_components=15;, score=-0.567 total time=   0.3s
[CV 2/10] END .................n_components=14;, score=-0.586 total time=   0.2s
[CV 6/10] END .................n_components=12;, score=-0.549 total time=   0.3s
[CV 4/10] END .................n_components=13;, score=-0.557 total time=   0.3s
[CV 9/10] END .................n_components=14;, score=-0.565 total time=   0.4s
[CV 9/10] END .................n_components=16;, score=-0.565 total time=   0.2s
[CV 5/10] END .................n_components=16;, score=-0.558 total time=   0.4s
[CV 8/10] END .................n_components=10;, score=-0.565 total time=   0.2s
[CV 1/10] END .................n_components=16;, score=-0.552 total time=   0.4s
[CV 3/10] END .................n_components=12;, score=-0.567 total time=   0.3s
[CV 3/10] END .................n_components=14;, score=-0.567 total time=   0.2s
[CV 8/10] END .................n_components=15;, score=-0.565 total time=   0.3s
[CV 1/10] END .................n_components=11;, score=-0.552 total time=   0.4s
[CV 8/10] END .................n_components=13;, score=-0.565 total time=   0.4s
[CV 4/10] END .................n_components=15;, score=-0.557 total time=   0.3s
[CV 3/10] END .................n_components=17;, score=-0.567 total time=   0.3s
[CV 10/10] END ................n_components=16;, score=-0.552 total time=   0.2s
[CV 7/10] END .................n_components=12;, score=-0.564 total time=   0.3s
[CV 9/10] END .................n_components=15;, score=-0.565 total time=   0.1s
[CV 4/10] END .................n_components=14;, score=-0.557 total time=   0.2s
[CV 5/10] END .................n_components=13;, score=-0.558 total time=   0.3s
[CV 6/10] END .................n_components=14;, score=-0.549 total time=   0.4s
[CV 4/10] END .................n_components=12;, score=-0.557 total time=   0.3s
[CV 1/10] END .................n_components=17;, score=-0.552 total time=   0.2s
[CV 6/10] END .................n_components=16;, score=-0.549 total time=   0.4s
[CV 10/10] END ................n_components=14;, score=-0.552 total time=   0.4s
[CV 10/10] END ................n_components=15;, score=-0.552 total time=   0.2s
[CV 2/10] END .................n_components=16;, score=-0.586 total time=   0.4s
[CV 2/10] END .................n_components=11;, score=-0.586 total time=   0.3s
[CV 1/10] END .................n_components=18;, score=-0.552 total time=   0.2s
[CV 4/10] END .................n_components=17;, score=-0.557 total time=   0.3s
[CV 7/10] END .................n_components=17;, score=-0.564 total time=   0.5s
[CV 8/10] END .................n_components=12;, score=-0.565 total time=   0.3s
[CV 9/10] END .................n_components=13;, score=-0.565 total time=   0.4s
[CV 9/10] END .................n_components=18;, score=-0.565 total time=   0.2s
[CV 2/10] END .................n_components=17;, score=-0.586 total time=   0.2s
[CV 6/10] END .................n_components=13;, score=-0.549 total time=   0.3s
[CV 5/10] END .................n_components=15;, score=-0.558 total time=   0.5s
[CV 2/10] END .................n_components=18;, score=-0.586 total time=   0.2s
[CV 7/10] END .................n_components=14;, score=-0.564 total time=   0.4s
[CV 5/10] END .................n_components=18;, score=-0.558 total time=   0.3s
[CV 10/10] END ................n_components=18;, score=-0.552 total time=   0.2s
[CV 7/10] END .................n_components=16;, score=-0.564 total time=   0.4s
[CV 3/10] END .................n_components=16;, score=-0.567 total time=   0.4s
[CV 5/10] END .................n_components=17;, score=-0.558 total time=   0.4s
[CV 1/10] END .................n_components=20;, score=-0.552 total time=   0.2s
[CV 1/10] END .................n_components=15;, score=-0.552 total time=   0.5s
[CV 3/10] END .................n_components=18;, score=-0.567 total time=   0.2s
[CV 1/10] END .................n_components=19;, score=-0.552 total time=   0.2s
[CV 10/10] END ................n_components=13;, score=-0.552 total time=   0.4s
[CV 3/10] END .................n_components=19;, score=-0.567 total time=   0.6s
[CV 7/10] END .................n_components=19;, score=-0.564 total time=   0.5s
[CV 6/10] END .................n_components=18;, score=-0.549 total time=   0.3s
[CV 2/10] END .................n_components=20;, score=-0.586 total time=   0.2s
[CV 6/10] END .................n_components=15;, score=-0.549 total time=   0.4s
[CV 8/10] END .................n_components=17;, score=-0.565 total time=   0.6s
[CV 2/10] END .................n_components=19;, score=-0.586 total time=   0.2s
[CV 8/10] END .................n_components=14;, score=-0.565 total time=   0.4s
[CV 5/10] END .................n_components=20;, score=-0.558 total time=   0.5s
[CV 8/10] END .................n_components=16;, score=-0.565 total time=   0.4s
[CV 6/10] END .................n_components=17;, score=-0.549 total time=   0.3s
[CV 4/10] END .................n_components=16;, score=-0.557 total time=   0.4s
[CV 4/10] END .................n_components=18;, score=-0.557 total time=   0.3s
[CV 3/10] END .................n_components=20;, score=-0.567 total time=   0.2s
[CV 7/10] END .................n_components=18;, score=-0.564 total time=   0.3s
[CV 7/10] END .................n_components=21;, score=-0.564 total time=   0.2s
[CV 2/10] END .................n_components=15;, score=-0.586 total time=   0.4s
[CV 9/10] END .................n_components=20;, score=-0.565 total time=   0.5s
[CV 9/10] END .................n_components=17;, score=-0.565 total time=   0.4s
[CV 8/10] END .................n_components=19;, score=-0.565 total time=   0.5s[CV 4/10] END .................n_components=19;, score=-0.557 total time=   0.5s

[CV 4/10] END .................n_components=20;, score=-0.557 total time=   0.3s
[CV 6/10] END .................n_components=20;, score=-0.549 total time=   0.5s
[CV 7/10] END .................n_components=23;, score=-0.564 total time=   0.4s
[CV 1/10] END .................n_components=22;, score=-0.552 total time=   0.5s
[CV 3/10] END .................n_components=21;, score=-0.567 total time=   0.6s
[CV 9/10] END .................n_components=22;, score=-0.565 total time=   0.5s
[CV 8/10] END .................n_components=21;, score=-0.565 total time=   0.4s
[CV 5/10] END .................n_components=22;, score=-0.558 total time=   0.6s
[CV 8/10] END .................n_components=18;, score=-0.565 total time=   0.4s
[CV 10/10] END ................n_components=17;, score=-0.552 total time=   0.3s
[CV 10/10] END ................n_components=20;, score=-0.552 total time=   0.4s
[CV 3/10] END .................n_components=23;, score=-0.567 total time=   0.6s
[CV 8/10] END .................n_components=23;, score=-0.565 total time=   0.2s
[CV 5/10] END .................n_components=24;, score=-0.558 total time=   0.3s
[CV 1/10] END .................n_components=24;, score=-0.552 total time=   0.7s
[CV 7/10] END .................n_components=20;, score=-0.564 total time=   0.5s
[CV 9/10] END .................n_components=21;, score=-0.565 total time=   0.4s
[CV 9/10] END .................n_components=19;, score=-0.565 total time=   0.6s
[CV 1/10] END .................n_components=21;, score=-0.552 total time=   0.3s
[CV 3/10] END .................n_components=25;, score=-0.567 total time=   0.4s
[CV 9/10] END .................n_components=23;, score=-0.565 total time=   0.3s
[CV 6/10] END .................n_components=24;, score=-0.549 total time=   0.2s
[CV 5/10] END .................n_components=19;, score=-0.558 total time=   0.7s
[CV 2/10] END .................n_components=22;, score=-0.586 total time=   0.6s
[CV 4/10] END .................n_components=21;, score=-0.557 total time=   0.6s
[CV 10/10] END ................n_components=22;, score=-0.552 total time=   0.6s
[CV 9/10] END .................n_components=24;, score=-0.565 total time=   0.6s
[CV 10/10] END ................n_components=21;, score=-0.552 total time=   0.2s
[CV 10/10] END ................n_components=23;, score=-0.552 total time=   0.2s
[CV 4/10] END .................n_components=25;, score=-0.557 total time=   0.2s
[CV 7/10] END .................n_components=24;, score=-0.564 total time=   0.2s
[CV 8/10] END .................n_components=20;, score=-0.565 total time=   0.4s
[CV 2/10] END .................n_components=21;, score=-0.586 total time=   0.4s
[CV 2/10] END .................n_components=24;, score=-0.586 total time=   0.5s
[CV 5/10] END .................n_components=25;, score=-0.558 total time=   0.2s
[CV 6/10] END .................n_components=22;, score=-0.549 total time=   0.8s
[CV 8/10] END .................n_components=24;, score=-0.565 total time=   0.2s
[CV 1/10] END .................n_components=26;, score=-0.552 total time=   0.3s
[CV 7/10] END .................n_components=25;, score=-0.564 total time=   0.3s
[CV 4/10] END .................n_components=23;, score=-0.557 total time=   0.8s
[CV 3/10] END .................n_components=22;, score=-0.567 total time=   0.4s
[CV 10/10] END ................n_components=19;, score=-0.552 total time=   0.6s
[CV 5/10] END .................n_components=21;, score=-0.558 total time=   0.5s
[CV 6/10] END .................n_components=25;, score=-0.549 total time=   0.2s
[CV 3/10] END .................n_components=27;, score=-0.567 total time=   0.2s
[CV 10/10] END ................n_components=24;, score=-0.552 total time=   0.5s
[CV 6/10] END .................n_components=19;, score=-0.549 total time=   0.7s
[CV 2/10] END .................n_components=26;, score=-0.586 total time=   0.3s
[CV 9/10] END .................n_components=26;, score=-0.565 total time=   0.4s
[CV 8/10] END .................n_components=25;, score=-0.565 total time=   0.3s

In [23]:
five_folds = []
folds = ["0", "1", "2", "3", "4"]
for modality in modalities:
    for fold in folds:
        pls = pd.read_csv(f'/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/rs/ica_main/fold_{fold}/models/csv/{modality}_fold_{fold}_PLS_result.csv', header=None)
        pls.columns = ['Fold', 'Modality', 'n components', 'MSE', 'MAE', 'R2', 'Pearson r']
        #pls.index = [modality] * len(pls)
        five_folds.append(pls)
        five_folds_all_modalities = pd.concat(five_folds, ignore_index=False)

five_folds_all_modalities['Pearson r'] = five_folds_all_modalities['Pearson r'].astype(str).str.replace(r'PearsonRResult\(statistic=|pvalue=|\)', '', regex=True)
five_folds_all_modalities[['Pearson r', 'p-value']] = five_folds_all_modalities['Pearson r'].str.split(',', expand=True).astype(float).round(decimals=3)
five_folds_all_modalities = five_folds_all_modalities.round(decimals=3)
#five_folds_all_modalities.to_csv('/media/hcs-sci-psy-narun/IBu/UK_BB/Cog-Ment/PLS/brain/dti/pls_5_folds_all_modalities.csv', index=False)
with pd.option_context('display.max_rows', None):
    display(five_folds_all_modalities)

,Fold,Modality,n components,MSE,MAE,R2,Pearson r,p-value
0,0,amplitudes_21,{'n_components': 5},0.493,0.561,0.020,0.141,0.0
0,1,amplitudes_21,{'n_components': 3},0.688,0.661,0.002,0.065,0.0
0,2,amplitudes_21,{'n_components': 5},0.776,0.706,0.007,0.085,0.0
0,3,amplitudes_21,{'n_components': 3},0.500,0.561,0.017,0.132,0.0
0,4,amplitudes_21,{'n_components': 5},0.515,0.564,0.018,0.138,0.0
0,0,amplitudes_55,{'n_components': 5},0.488,0.558,0.028,0.169,0.0
0,1,amplitudes_55,{'n_components': 3},0.683,0.659,0.009,0.100,0.0
0,2,amplitudes_55,{'n_components': 3},0.770,0.701,0.014,0.121,0.0
0,3,amplitudes_55,{'n_components': 4},0.494,0.558,0.029,0.172,0.0
0,4,amplitudes_55,{'n_components': 3},0.516,0.566,0.017,0.136,0.0
0,0,full_correlation_21,{'n_components': 12},0.468,0.545,0.068,0.262,0.0
0,1,full_correlation_21,{'n_components': 6},0.671,0.654,0.027,0.169,0.0
0,2,full_correlation_21,{'n_components': 6},0.757,0.696,0.031,0.178,0.0
0,3,full_correlation_21,{'n_components': 16},0.484,0.551,0.049,0.227,0.0
0,4,full_correlation_21,{'n_components': 15},0.500,0.557,0.047,0.223,0.0
0,0,full_correlation_55,{'n_components': 4},0.462,0.542,0.080,0.289,0.0
0,1,full_correlation_55,{'n_components': 3},0.671,0.654,0.026,0.184,0.0
0,2,full_correlation_55,{'n_components': 3},0.749,0.690,0.041,0.207,0.0
0,3,full_correlation_55,{'n_components': 4},0.475,0.546,0.067,0.268,0.0
0,4,full_correlation_55,{'n_components': 4},0.486,0.550,0.074,0.278,0.0
0,0,partial_correlation_21,{'n_components': 4},0.466,0.544,0.073,0.271,0.0
0,1,partial_correlation_21,{'n_components': 3},0.669,0.652,0.030,0.179,0.0
0,2,partial_correlation_21,{'n_components': 3},0.752,0.694,0.037,0.193,0.0
0,3,partial_correlation_21,{'n_components': 4},0.484,0.552,0.049,0.226,0.0
0,4,partial_correlation_21,{'n_components': 4},0.497,0.555,0.053,0.235,0.0
0,0,partial_correlation_55,{'n_components': 3},0.444,0.533,0.116,0.344,0.0
0,1,partial_correlation_55,{'n_components': 2},0.661,0.649,0.040,0.221,0.0
0,2,partial_correlation_55,{'n_components': 2},0.743,0.688,0.049,0.230,0.0
0,3,partial_correlation_55,{'n_components': 3},0.466,0.541,0.084,0.304,0.0
0,4,partial_correlation_55,{'n_components': 3},0.476,0.545,0.093,0.312,0.0

In [24]:
# Average across folds
five_folds_all_modalities_mean = five_folds_all_modalities[['R2', 'Pearson r', 'Modality', 'MSE', 'MAE']]
five_folds_all_modalities_mean.groupby(['Modality']).mean().round(3).sort_values(by='R2', ascending=False)

                           R2  Pearson r    MSE    MAE
Modality
partial_correlation_55  0.076      0.282  0.558  0.591
full_correlation_55     0.058      0.245  0.569  0.596
partial_correlation_21  0.048      0.221  0.574  0.599
full_correlation_21     0.044      0.212  0.576  0.601
amplitudes_55           0.019      0.140  0.590  0.608
amplitudes_21           0.013      0.112  0.594  0.611